import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'de' | 'fr' | 'ar' | 'fa' | 'ps';

export interface Language {
    code: LanguageCode;
    name: string;
    flag: string;
    dir: 'ltr' | 'rtl';
}

export const LANGUAGES: Language[] = [
    { code: 'en', name: 'English', flag: '🇬🇧', dir: 'ltr' },
    { code: 'de', name: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
    { code: 'fr', name: 'Français', flag: '🇫🇷', dir: 'ltr' },
    { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
    { code: 'fa', name: 'فارسی', flag: '🇮🇷', dir: 'rtl' },
    { code: 'ps', name: 'پښتو', flag: '🇦🇫', dir: 'rtl' }
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
    en: {
        home: "Home", services: "Services", portfolio: "Portfolio",
        pricing: "Pricing", contact: "Contact", lets_talk: "Let's Talk",
        banner_title: "From Simple Idea to Captivating Video",
        banner_subtitle: "15 years of bringing ideas to life. I help brands tell unforgettable stories through motion graphics, 2D animation, and explainer videos.",
        hire_me: "Hire Me Now", watch_showreel: "Watch Showreel",
        services_sub: "Services", services_title: "Premium Creative Solutions",
        explore: "Explore",
        about_sub: "Creative Storytelling", about_title: "Crafting Motion that Defines Your Brand",
        about_p1: "At Smoooth Pixel, we don't just animate; we breathe life into ideas. As a senior motion graphics specialist, I blend 15 years of industry-leading expertise with cutting-edge visual technology to create cinematic experiences that resonate globally.",
        about_p2: "Our philosophy is simple: Elegance in Motion. Whether it's high-end corporate identities, complex 3D technical visualizations, or fast-paced social media campaigns, we deliver pixel-perfect results that leave a lasting impact.",
        view_showreel: "View Showreel",
        years_experience: "Years Experience", projects_done: "Projects Done",
        clients: "Clients", satisfied_globally: "Satisfied Globally",
        facts_sub: "Tools & Software", facts_title: "Software We Master",
        team_sub: "Creative Collective", team_title: "Meet the Architects of Motion",
        view_resume: "View Resume",
        contact_title: "Contact Me",
        contact_name: "Name", contact_email: "Email*", contact_phone: "Phone",
        contact_telegram: "Telegram @username", contact_message: "Tell Us About Project *",
        contact_submit: "Get in Touch", contact_sending: "Sending…",
        ready_for_work: "Ready for work",
        years_expert: "YEARS\nEXPERT",
        senior_expert: "Senior Motion Graphics & 3D Visualization Expert",
        official_email: "Official Email",
        telegram_support: "Telegram Support",
        portfolio_sub: "Selected Works", portfolio_title: "Our Latest Projects",
        showreel_sub: "Behind the Scenes", showreel_title: "Watch Our Showreel",
        pricing_sub: "Packages", pricing_title: "Simple Transparent Pricing",
        copyright: "All Rights Reserved",
        back_to_roster: "Back to Roster", key_proficiencies: "Key Proficiencies",
        work_history: "Work History", my_expertise: "My Expertise",
        academic_background: "Academic Background", education: "Education",
        no_timeline_entries: "No entries listed yet.",
        loading_profile: "Loading creative profile...", profile_error: "Profile Error",
        back_to_home: "Back to Home",
        creative_designer_bio: "Creative designer and crucial architect of motion, styling stunning cinematic experiences.",
        
        // New Keys
        work: "Work", team: "Team", reviews: "Reviews", price_calculator: "Price Calculator", about: "About",
        animation_motion: "Animation & Motion", saas_explainers: "SaaS & Explainers", video_production: "Video Production",
        estimate_budget: "Estimate budget", pricing_packages: "Pricing packages", overview: "Overview",
        free_consultation: "Free consultation", our_expertise: "Our expertise",
        expertise_desc: "Premium 3D animation, SaaS explainers, and cinematic video production for ambitious brands.",
        all: "All", view_all_projects: "View All Projects", order_now: "Order Now",
        loading_packages: "Loading premium packages...", no_packages_available: "No pricing packages are currently available.",
        details_coming_soon: "Package details coming soon. Contact us for a custom quote.",
        cost_estimator: "Cost Estimator", investment_visualization: "Investment Visualization",
        calculator_desc: "Use our high-precision algorithm to estimate the resource allocation for your creative project. All estimates are subject to final creative brief analysis.",
        estimated_total: "Estimated Total", estimated_delivery: "Est. Delivery (Days)",
        project_stream: "Project Stream", temporal_duration: "Temporal Duration",
        structural_complexity: "Structural Complexity", level: "Level",
        accelerated_deployment: "Accelerated Deployment", fast_turnaround_desc: "30% faster turnaround",
        initiate_quote: "Initiate Full Quote", stream_animation: "Animation", stream_explainer: "Explainer", stream_3d: "3D Animation",
        review_sub: "Client Sentiment", review_title: "Client Testimonials", write_review: "Write a Review",
        live_verification: "Live Business Verification", google_reviews_title: "SmooothPixel Google Reviews",
        directions: "Directions", save: "Save", telegram: "Telegram", open_24_hours: "Open 24 hours",
        write_review_btn: "Write a review", google_reviews_count: "Google reviews",
        posting_publicly: "Posting publicly across Google", share_experience_placeholder: "Share details of your own experience at this place",
        change_photo: "Change Photo", add_photo_video: "Add photos and videos",
        reviewer_details_title: "Your Reviewer Details", your_name_placeholder: "Your Name (Required) *",
        company_project_placeholder: "Company / Project (Optional)", website_url_placeholder: "Website URL (Optional)",
        cancel: "Cancel", post: "Post", posting: "Posting...", website_review: "Website Review", google_review: "Google Review",
        review_submitted_title: "Review Submitted!", review_submitted_desc: "Your review was submitted successfully and sent to moderation. Thank you for your feedback!",
        helpful: "Helpful", less: " Less", more: " More", local_guide: "Local Guide",
        freelance_promo: "Hello👋 i'm available for freelance work", quick_response: "For quick response:",
                rating_terrible: "Terrible", rating_poor: "Poor", rating_average: "Average", rating_good: "Good", rating_excellent: "Excellent",
        studio_subtitle: "Animation & Motion Graphics Studio",
        your_name: "Your Name *",
        website_link_optional: "Website Link (Optional)",
        social_profile_optional: "Social Profile (Optional)",
        profile_photo_optional: "Profile Photo (Optional)",
        click_stars_to_rate: "Click stars to rate",
        review_deck_desc: "This review will appear on our home page slide deck",
        submit_website_testimonial: "Submit Website Testimonial",
        enter_name_placeholder: "Enter your name (e.g. Felix)",
        describe_project_placeholder: "Describe your creative project with SmooothPixel, quality of work, and delivery speed...",
        company_name_placeholder: "e.g. SmooothPixel Co.",
        tier_basic: "Basic",
        tier_standard: "Standard",
        tier_premium: "Premium"
    },
    de: {
        home: "Startseite", services: "Dienstleistungen", portfolio: "Portfolio",
        pricing: "Preise", contact: "Kontakt", lets_talk: "Lass uns reden",
        banner_title: "Von der einfachen Idee zum fesselnden Video",
        banner_subtitle: "15 Jahre Erfahrung im Erwecken von Ideen. Ich helfe Marken, unvergeßliche Geschichten durch Motion Graphics, 2D-Animation und Erklärvideos zu erzählen.",
        hire_me: "Jetzt anheuern", watch_showreel: "Showreel ansehen",
        services_sub: "Dienstleistungen", services_title: "Premium-Kreativlösungen",
        explore: "Erkunden",
        about_sub: "Kreatives Erzählen", about_title: "Bewegungen gestalten, die Ihre Marke definieren",
        about_p1: "Bei Smoooth Pixel animieren wir nicht nur – wir hauchen Ideen Leben ein. Als Senior Motion Graphics Spezialist verbinde ich 15 Jahre branchenführendes Know-how mit modernster visueller Technologie.",
        about_p2: "Unsere Philosophie ist einfach: Eleganz in Bewegung. Ob hochkarätige Unternehmensidentitäten, komplexe 3D-Visualisierungen oder schnelle Social-Media-Kampagnen – wir liefern pixelgenaue Ergebnisse.",
        view_showreel: "Showreel ansehen",
        years_experience: "Jahre Erfahrung", projects_done: "Projekte abgeschlossen",
        clients: "Kunden", satisfied_globally: "Weltweit zufrieden",
        facts_sub: "Tools & Software", facts_title: "Software, die wir beherrschen",
        team_sub: "Kreatives Kollektiv", team_title: "Die Architekten der Bewegung",
        view_resume: "Lebenslauf ansehen",
        contact_title: "Kontaktiere mich",
        contact_name: "Name", contact_email: "E-Mail*", contact_phone: "Telefon",
        contact_telegram: "Telegram @username", contact_message: "Erzählen Sie uns von Ihrem Projekt *",
        contact_submit: "Kontakt aufnehmen", contact_sending: "Senden…",
        ready_for_work: "Bereit für Arbeit",
        years_expert: "JAHRE\nEXPERTE",
        senior_expert: "Senior Motion Graphics & 3D-Visualisierungsexperte",
        official_email: "Offizielle E-Mail", telegram_support: "Telegram-Support",
        portfolio_sub: "Ausgewählte Arbeiten", portfolio_title: "Unsere neuesten Projekte",
        showreel_sub: "Hinter den Kulissen", showreel_title: "Unser Showreel ansehen",
        pricing_sub: "Pakete", pricing_title: "Einfache transparente Preisgestaltung",
        copyright: "Alle Rechte vorbehalten",
        back_to_roster: "Zurück zur Liste", key_proficiencies: "Schlüsselkompetenzen",
        work_history: "Werdegang", my_expertise: "Meine Expertise",
        academic_background: "Akademischer Hintergrund", education: "Ausbildung",
        no_timeline_entries: "Noch keine Einträge vorhanden.",
        loading_profile: "Kreatives Profil wird geladen...", profile_error: "Profilfehler",
        back_to_home: "Zurück zur Startseite",
        creative_designer_bio: "Kreativer Designer und wichtiger Architekt der Bewegung.",
        
        // New Keys
        work: "Arbeiten", team: "Team", reviews: "Bewertungen", price_calculator: "Preiskalkulator", about: "Über uns",
        animation_motion: "Animation & Bewegung", saas_explainers: "SaaS & Erklärfilme", video_production: "Videoproduktion",
        estimate_budget: "Budget schätzen", pricing_packages: "Preispakete", overview: "Übersicht",
        free_consultation: "Kostenlose Beratung", our_expertise: "Unsere Kompetenz",
        expertise_desc: "Premium 3D-Animationen, SaaS-Erklärvideos und kinoreife Videoproduktion für ambitionierte Marken.",
        all: "Alle", view_all_projects: "Alle Projekte anzeigen", order_now: "Jetzt bestellen",
        loading_packages: "Premium-Pakete werden geladen...", no_packages_available: "Derzeit sind keine Preispakete verfügbar.",
        details_coming_soon: "Paketdetails folgen in Kürze. Kontaktieren Sie uns für ein individuelles Angebot.",
        cost_estimator: "Kostenrechner", investment_visualization: "Investitionsvisualisierung",
        calculator_desc: "Verwenden Sie unseren hochpräzisen Algorithmus, um die Ressourcenzuweisung für Ihr kreatives Projekt zu schätzen. Alle Schätzungen vorbehaltlich der endgültigen Analyse.",
        estimated_total: "Geschätzte Summe", estimated_delivery: "Geschätzte Lieferzeit (Tage)",
        project_stream: "Projektbereich", temporal_duration: "Zeitdauer",
        structural_complexity: "Strukturelle Komplexität", level: "Stufe",
        accelerated_deployment: "Beschleunigte Bereitstellung", fast_turnaround_desc: "30% schnellere Bearbeitung",
        initiate_quote: "Vollständiges Angebot anfordern", stream_animation: "Animation", stream_explainer: "Erklärvideo", stream_3d: "3D-Animation",
        review_sub: "Kundenmeinungen", review_title: "Kundenreferenzen", write_review: "Bewertung schreiben",
        live_verification: "Live-Unternehmensprüfung", google_reviews_title: "SmooothPixel Google-Bewertungen",
        directions: "Wegbeschreibung", save: "Speichern", telegram: "Telegram", open_24_hours: "24 Stunden geöffnet",
        write_review_btn: "Bewertung schreiben", google_reviews_count: "Google-Bewertungen",
        posting_publicly: "Wird öffentlich auf Google gepostet", share_experience_placeholder: "Teilen Sie Details zu Ihrer eigenen Erfahrung",
        change_photo: "Foto ändern", add_photo_video: "Fotos und Videos hinzufügen",
        reviewer_details_title: "Ihre Bewerterdetails", your_name_placeholder: "Ihr Name (Erforderlich) *",
        company_project_placeholder: "Firma / Projekt (Optional)", website_url_placeholder: "Website-URL (Optional)",
        cancel: "Abbrechen", post: "Posten", posting: "Wird gepostet...", website_review: "Website-Bewertung", google_review: "Google-Bewertung",
        review_submitted_title: "Bewertung abgeschickt!", review_submitted_desc: "Ihre Bewertung wurde erfolgreich übermittelt und an die Moderation gesendet. Vielen Dank für Ihr Feedback!",
        helpful: "Hilfreich", less: " Weniger", more: " Mehr", local_guide: "Local Guide",
        freelance_promo: "Hallo👋 Ich bin für freiberufliche Projekte verfügbar", quick_response: "Für eine schnelle Antwort:",
                rating_terrible: "Schrecklich", rating_poor: "Schlecht", rating_average: "Durchschnittlich", rating_good: "Gut", rating_excellent: "Hervorragend",
        studio_subtitle: "Animations- & Motion-Graphics-Studio",
        your_name: "Ihr Name *",
        website_link_optional: "Website-Link (Optional)",
        social_profile_optional: "Soziales Profil (Optional)",
        profile_photo_optional: "Profilbild (Optional)",
        click_stars_to_rate: "Klicken Sie auf die Sterne, um zu bewerten",
        review_deck_desc: "Diese Bewertung wird auf unserer Startseite angezeigt",
        submit_website_testimonial: "Website-Referenz senden",
        enter_name_placeholder: "Geben Sie Ihren Namen ein (z. B. Felix)",
        describe_project_placeholder: "Beschreiben Sie Ihr kreatives Projekt mit SmooothPixel, die Qualität der Arbeit und die Liefergeschwindigkeit...",
        company_name_placeholder: "z. B. SmooothPixel Co.",
        tier_basic: "Basis",
        tier_standard: "Standard",
        tier_premium: "Premium"
    },
    fr: {
        home: "Accueil", services: "Services", portfolio: "Portfolio",
        pricing: "Tarifs", contact: "Contact", lets_talk: "Parlons-en",
        banner_title: "D'une simple idée à une vidéo captivante",
        banner_subtitle: "15 ans à donner vie aux idées. J'aide les marques à raconter des histoires inoubliables grâce au motion design, à l'animation 2D et aux vidéos explicatives.",
        hire_me: "Engagez-moi", watch_showreel: "Voir le Showreel",
        services_sub: "Services", services_title: "Solutions Créatives Premium",
        explore: "Explorer",
        about_sub: "Narration Créative", about_title: "Créer des mouvements qui définissent votre marque",
        about_p1: "Chez Smoooth Pixel, nous ne faisons pas qu'animer – nous insufflons la vie aux idées. En tant que spécialiste senior en motion graphics, je combine 15 ans d'expertise avec la technologie visuelle la plus avancée.",
        about_p2: "Notre philosophie est simple : l'élégance en mouvement. Qu'il s'agisse d'identités d'entreprise haut de gamme ou de campagnes sur les réseaux sociaux, nous livrons des résultats parfaits au pixel près.",
        view_showreel: "Voir le Showreel",
        years_experience: "Années d'expérience", projects_done: "Projets réalisés",
        clients: "Clients", satisfied_globally: "Satisfaits dans le monde entier",
        facts_sub: "Outils & Logiciels", facts_title: "Logiciels que nous maîtrisons",
        team_sub: "Collectif Créatif", team_title: "Rencontrez les Architectes du Mouvement",
        view_resume: "Voir le CV",
        contact_title: "Contactez-moi",
        contact_name: "Nom", contact_email: "Email*", contact_phone: "Téléphone",
        contact_telegram: "Telegram @username", contact_message: "Parlez-nous de votre projet *",
        contact_submit: "Prendre contact", contact_sending: "Envoi…",
        ready_for_work: "Prêt pour le travail",
        years_expert: "ANS\nEXPERT",
        senior_expert: "Expert Senior en Motion Graphics & Visualisation 3D",
        official_email: "Email officiel", telegram_support: "Support Telegram",
        portfolio_sub: "Travaux sélectionnés", portfolio_title: "Nos derniers projets",
        showreel_sub: "Dans les coulisses", showreel_title: "Regardez notre Showreel",
        pricing_sub: "Forfaits", pricing_title: "Tarification simple et transparente",
        copyright: "Tous droits réservés",
        back_to_roster: "Retour à l'équipe", key_proficiencies: "Compétences clés",
        work_history: "Expérience professionnelle", my_expertise: "Mon Expertise",
        academic_background: "Parcours académique", education: "Éducation",
        no_timeline_entries: "Aucune entrée répertoriée pour le moment.",
        loading_profile: "Chargement du profil créatif...", profile_error: "Erreur de profil",
        back_to_home: "Retour à l'accueil",
        creative_designer_bio: "Designer créatif et architecte essentiel du mouvement.",
        
        // New Keys
        work: "Travaux", team: "Équipe", reviews: "Avis", price_calculator: "Calculateur", about: "À propos",
        animation_motion: "Animation & Motion", saas_explainers: "SaaS & Explicatives", video_production: "Production Vidéo",
        estimate_budget: "Estimer le budget", pricing_packages: "Forfaits", overview: "Présentation",
        free_consultation: "Consultation gratuite", our_expertise: "Notre expertise",
        expertise_desc: "Animation 3D premium, vidéos explicatives SaaS et production vidéo cinématographique pour marques ambitieuses.",
        all: "Tous", view_all_projects: "Voir tous les projets", order_now: "Commander",
        loading_packages: "Chargement des forfaits premium...", no_packages_available: "Aucun forfait n'est disponible pour le moment.",
        details_coming_soon: "Détails à venir. Contactez-nous pour un devis personnalisé.",
        cost_estimator: "Estimateur de coûts", investment_visualization: "Visualisation de l'investissement",
        calculator_desc: "Utilisez notre algorithme de haute précision pour estimer l'allocation des ressources de votre projet. Les estimations sont sujettes à l'analyse finale.",
        estimated_total: "Total estimé", estimated_delivery: "Livraison est. (Jours)",
        project_stream: "Type de projet", temporal_duration: "Durée temporelle",
        structural_complexity: "Complexité structurelle", level: "Niveau",
        accelerated_deployment: "Déploiement accéléré", fast_turnaround_desc: "Délai 30% plus rapide",
        initiate_quote: "Demander un devis complet", stream_animation: "Animation", stream_explainer: "Explainer", stream_3d: "Animation 3D",
        review_sub: "Avis des clients", review_title: "Témoignages clients", write_review: "Écrire un avis",
        live_verification: "Vérification en direct", google_reviews_title: "Avis Google SmooothPixel",
        directions: "Itinéraire", save: "Enregistrer", telegram: "Telegram", open_24_hours: "Ouvert 24h/24",
        write_review_btn: "Écrire un avis", google_reviews_count: "Avis Google",
        posting_publicly: "Publication publique sur Google", share_experience_placeholder: "Partagez les détails de votre propre expérience",
        change_photo: "Modifier la photo", add_photo_video: "Ajouter des photos/vidéos",
        reviewer_details_title: "Vos coordonnées", your_name_placeholder: "Votre nom (Requis) *",
        company_project_placeholder: "Entreprise / Projet (Optionnel)", website_url_placeholder: "URL du site (Optionnel)",
        cancel: "Annuler", post: "Publier", posting: "Publication...", website_review: "Avis du site", google_review: "Avis Google",
        review_submitted_title: "Avis envoyé !", review_submitted_desc: "Votre avis a été soumis avec succès et envoyé pour modération. Merci pour vos commentaires !",
        helpful: "Utile", less: " Moins", more: " Plus", local_guide: "Local Guide",
        freelance_promo: "Bonjour👋 Je suis disponible en freelance", quick_response: "Pour une réponse rapide :",
                rating_terrible: "Terrible", rating_poor: "Médiocre", rating_average: "Moyen", rating_good: "Bon", rating_excellent: "Excellent",
        studio_subtitle: "Studio d'Animation & Motion Design",
        your_name: "Votre Nom *",
        website_link_optional: "Lien du site (Optionnel)",
        social_profile_optional: "Profil social (Optionnel)",
        profile_photo_optional: "Photo de profil (Optionnel)",
        click_stars_to_rate: "Cliquez sur les étoiles pour évaluer",
        review_deck_desc: "Cet avis apparaîtra sur le carrousel de notre page d'accueil",
        submit_website_testimonial: "Soumettre un témoignage de site",
        enter_name_placeholder: "Entrez votre nom (ex. Felix)",
        describe_project_placeholder: "Décrivez votre projet créatif avec SmooothPixel, la qualité du travail et la rapidité de livraison...",
        company_name_placeholder: "ex. SmooothPixel Co.",
        tier_basic: "De Base",
        tier_standard: "Standard",
        tier_premium: "Premium"
    },
    ar: {
        home: "الرئيسية", services: "الخدمات", portfolio: "الأعمال",
        pricing: "الأسعار", contact: "اتصل بنا", lets_talk: "فلنتحدث",
        banner_title: "من فكرة بسيطة إلى فيديو آسر",
        banner_subtitle: "15 عامًا من إحياء الأفكار. أساعد العلامات التجارية على سرد قصص لا تُنسى من خلال الرسوم المتحركة والأنيمشين.",
        hire_me: "وظفني الآن", watch_showreel: "شاهد العرض التقديمي",
        services_sub: "الخدمات", services_title: "حلول إبداعية متميزة",
        explore: "استكشف",
        about_sub: "سرد إبداعي", about_title: "صياغة حركة تُعرِف علامتك التجارية",
        about_p1: "في Smoooth Pixel، نحن لا نُحرك فقط — بل نبث الحياة في الأفكار. بصفتي متخصصًا رئيسيًا في الرسوم المتحركة، أدمج 15 عامًا من الخبرة مع أحدث التقنيات.",
        about_p2: "فلسفتنا بسيطة: الأناقة في الحركة. سواء كانت هويات الشركات الراقية أو حملات وسائل التواصل الاجتماعي، نقدم نتائج مثالية تترك أثرًا دائمًا.",
        view_showreel: "مشاهدة العرض التقديمي",
        years_experience: "سنوات الخبرة", projects_done: "المشاريع المنجزة",
        clients: "العملاء", satisfied_globally: "راضون عالميًا",
        facts_sub: "الأدوات والبرامج", facts_title: "البرامج التي نتقنها",
        team_sub: "المجموعة الإبداعية", team_title: "تعرَّف على مهندسي الحركة",
        view_resume: "عرض السيرة الذاتية",
        contact_title: "تواصل معي",
        contact_name: "الاسم", contact_email: "البريد الإلكتروني*", contact_phone: "الهاتف",
        contact_telegram: "تيليجرام @username", contact_message: "أخبرنا عن مشروعك *",
        contact_submit: "تواصل معنا", contact_sending: "جاري الإرسال…",
        ready_for_work: "مستعد للعمل",
        years_expert: "سنوات\nخبير",
        senior_expert: "خبير رئيسي في الرسوم المتحركة والتصوير ثلاثي الأبعاد",
        official_email: "البريد الرسمي", telegram_support: "دعم تيليجرام",
        portfolio_sub: "أعمال مختارة", portfolio_title: "أحدث مشاريعنا",
        showreel_sub: "خلف الكواليس", showreel_title: "شاهد عرضنا التقديمي",
        pricing_sub: "الباقات", pricing_title: "تسعير بسيط وشفاف",
        copyright: "جميع الحقوق محفوظة",
        back_to_roster: "العودة إلى الفريق", key_proficiencies: "الكفاءات الرئيسية",
        work_history: "تاريخ العمل", my_expertise: "خبرتي",
        academic_background: "الخلفية الأكاديمية", education: "التعليم",
        no_timeline_entries: "لم يتم إدراج أي مدخلات بعد.",
        loading_profile: "جاري تحميل الملف الإبداعي...", profile_error: "خطأ في الملف الشخصي",
        back_to_home: "العودة إلى الرئيسية",
        creative_designer_bio: "مصمم إبداعي ومهندس حركة محوري، يصمم تجارب سينمائية مذهلة.",
        
        // New Keys
        work: "الأعمال", team: "الفريق", reviews: "التقييمات", price_calculator: "حاسبة الأسعار", about: "عنّا",
        animation_motion: "الرسوم المتحركة والحركة", saas_explainers: "فيديوهات SaaS والتوضيحية", video_production: "إنتاج الفيديو",
        estimate_budget: "تقدير الميزانية", pricing_packages: "باقات الأسعار", overview: "لمحة عامة",
        free_consultation: "استشارة مجانية", our_expertise: "خبراتنا",
        expertise_desc: "رسوم متحركة ثلاثية الأبعاد متميزة، فيديوهات توضيحية لـ SaaS، وإنتاج فيديو سينمائي للعلامات التجارية الطموحة.",
        all: "الكل", view_all_projects: "عرض جميع المشاريع", order_now: "اطلب الآن",
        loading_packages: "جاري تحميل الباقات المتميزة...", no_packages_available: "لا توجد باقات أسعار متاحة حالياً.",
        details_coming_soon: "تفاصيل الباقة قريباً. اتصل بنا للحصول على عرض مخصص.",
        cost_estimator: "حاسبة التكلفة", investment_visualization: "تقدير الاستثمار",
        calculator_desc: "استخدم خوارزميتنا عالية الدقة لتقدير تخصيص الموارد لمشروعك الإبداعي. جميع التقديرات تخضع للتحليل النهائي للمشروع.",
        estimated_total: "الإجمالي التقديري", estimated_delivery: "التسليم المتوقع (أيام)",
        project_stream: "مسار المشروع", temporal_duration: "المدة الزمنية",
        structural_complexity: "التعقيد الهيكلي", level: "مستوى",
        accelerated_deployment: "التسليم السريع", fast_turnaround_desc: "تسليم أسرع بنسبة 30%",
        initiate_quote: "بدء طلب عرض سعر", stream_animation: "رسوم متحركة", stream_explainer: "فيديو توضيحي", stream_3d: "رسوم ثلاثية الأبعاد",
        review_sub: "آراء العملاء", review_title: "شهادات العملاء", write_review: "كتابة تقييم",
        live_verification: "التحقق المباشر من العمل", google_reviews_title: "تقييمات جوجل لـ SmooothPixel",
        directions: "الاتجاهات", save: "حفظ", telegram: "تيليجرام", open_24_hours: "مفتوح 24 ساعة",
        write_review_btn: "كتابة مراجعة", google_reviews_count: "تقييمات جوجل",
        posting_publicly: "نشر علني على جوجل", share_experience_placeholder: "شارك تفاصيل تجربتك الخاصة في هذا المكان",
        change_photo: "تغيير الصورة", add_photo_video: "إضافة صور وفيديو",
        reviewer_details_title: "تفاصيل المراجع الخاص بك", your_name_placeholder: "اسمك (مطلوب) *",
        company_project_placeholder: "الشركة / المشروع (اختياري)", website_url_placeholder: "رابط الموقع (اختياري)",
        cancel: "إلغاء", post: "نشر", posting: "جاري النشر...", website_review: "تقييم الموقع", google_review: "تقييم جوجل",
        review_submitted_title: "تم تقديم التقييم!", review_submitted_desc: "تم تقديم تقييمك بننجاح وإرساله للمراجعة. شكراً لتعليقاتك!",
        helpful: "مفيد", less: " أقل", more: " المزيد", local_guide: "مرشد محلي",
        freelance_promo: "مرحباً👋 أنا متاح للعمل الحر", quick_response: "للإجابة السريعة:",
                rating_terrible: "سيء جداً", rating_poor: "سيء", rating_average: "متوسط", rating_good: "جيد", rating_excellent: "ممتاز",
        studio_subtitle: "استوديو الرسوم المتحركة وموشن جرافيك",
        your_name: "اسمك *",
        website_link_optional: "رابط الموقع الإلكتروني (اختياري)",
        social_profile_optional: "الملف الشخصي الاجتماعي (اختياري)",
        profile_photo_optional: "صورة الملف الشخصي (اختياري)",
        click_stars_to_rate: "انقر فوق النجوم للتقييم",
        review_deck_desc: "ستظهر هذه المراجعة في معرض الصفحة الرئيسية",
        submit_website_testimonial: "تقديم شهادة للموقع",
        enter_name_placeholder: "أدخل اسمك (مثل يوسف)",
        describe_project_placeholder: "صف مشروعك الإبداعي مع SmooothPixel، وجودة العمل، وسرعة التسليم...",
        company_name_placeholder: "مثل شركة SmooothPixel",
        tier_basic: "أساسي",
        tier_standard: "قياسي",
        tier_premium: "مميز"
    },
    fa: {
        home: "صفحه اصلی", services: "خدمات", portfolio: "نمونه کارها",
        pricing: "قیمت‌گذاری", contact: "تماس با ما", lets_talk: "گفتگو کنیم",
        banner_title: "از ایده‌ای ساده تا ویدیویی جذاب",
        banner_subtitle: "۱۵ سال تجربه در جان بخشیدن به ایده‌ها. به برندها کمک می‌کنم داستان‌های فراموش‌نشدنی روایت کنند.",
        hire_me: "همین الان استخدام کنید", watch_showreel: "مشاهده شورئیل",
        services_sub: "خدمات", services_title: "راه‌حل‌های خلاقانه ممتاز",
        explore: "کاوش",
        about_sub: "داستان‌سرایی خلاق", about_title: "خلق حرکتی که برند شما را تعریف می‌کند",
        about_p1: "در Smoooth Pixel ما فقط انیمیت نمی‌کنیم؛ به ایده‌ها جان می‌دهیم. به عنوان متخصص ارشد موشن گرافیک، ۱۵ سال تجربه پیشرو را با فناوری بصری پیشرفته ترکیب می‌کنم.",
        about_p2: "فلسفه ما ساده است: ظرافت در حرکت. چه هویت‌های سازمانی سطح بالا چه کمپین‌های سریع رسانه‌های اجتماعی – نتایج بی‌نقص ارائه می‌دهیم.",
        view_showreel: "مشاهده شورئیل",
        years_experience: "سال تجربه", projects_done: "پروژه انجام شده",
        clients: "مشتری", satisfied_globally: "راضی در سراسر جهان",
        facts_sub: "ابزارها و نرم‌افزارها", facts_title: "نرم‌افزارهایی که بر آن‌ها مسلط هستیم",
        team_sub: "جمع خلاق", team_title: "با معماران حرکت آشنا شوید",
        view_resume: "مشاهده رزومه",
        contact_title: "با من تماس بگیرید",
        contact_name: "نام", contact_email: "ایمیل*", contact_phone: "تلفن",
        contact_telegram: "تلگرام @username", contact_message: "درباره پروژه‌تان بگویید *",
        contact_submit: "ارتباط برقرار کنید", contact_sending: "در حال ارسال…",
        ready_for_work: "آماده کار",
        years_expert: "سال\nتجربه",
        senior_expert: "متخصص ارشد موشن گرافیک و ویژوالیزیشن سه‌بعدی",
        official_email: "ایمیل رسمی", telegram_support: "پشتیبانی تلگرام",
        portfolio_sub: "آثار منتخب", portfolio_title: "جدیدترین پروژه‌های ما",
        showreel_sub: "پشت صحنه", showreel_title: "شورئیل ما را تماشا کنید",
        pricing_sub: "بسته‌ها", pricing_title: "قیمت‌گذاری ساده و شفاف",
        copyright: "تمامی حقوق محفوظ است",
        back_to_roster: "بازگشت به لیست", key_proficiencies: "مهارت‌های کلیدی",
        work_history: "سوابق کاری", my_expertise: "تخصص من",
        academic_background: "پیشینه تحصیلی", education: "تحصیلات",
        no_timeline_entries: "هنوز هیچ موردی ثبت نشده است.",
        loading_profile: "در حال بارگذاری پروفایل خلاق...", profile_error: "خطا در پروفایل",
        back_to_home: "بازگشت به صفحه اصلی",
        creative_designer_bio: "طراح خلاق و معمار محوری حرکت، با خلق تجربیات سینمایی خیره‌کننده.",
        
        // New Keys
        work: "نمونه کارها", team: "تیم ما", reviews: "نظرات", price_calculator: "محاسبه قیمت", about: "درباره ما",
        animation_motion: "انیمیشن و موشن", saas_explainers: "ویدیوهای توضیحاتی و SaaS", video_production: "تولید ویدیو",
        estimate_budget: "تخمین بودجه", pricing_packages: "بسته‌های قیمت‌گذاری", overview: "بررسی کلی",
        free_consultation: "مشاوره رایگان", our_expertise: "تخصص ما",
        expertise_desc: "انیمیشن سه‌بعدی ممتاز، ویدیوهای توضیحی محصول و تولید ویدیوهای سینمایی برای برندهای جاه‌طلب.",
        all: "همه", view_all_projects: "مشاهده همه پروژه‌ها", order_now: "سفارش دهید",
        loading_packages: "در حال بارگذاری بسته‌های ویژه...", no_packages_available: "در حال حاضر هیچ بسته قیمت‌گذاری در دسترس نیست.",
        details_coming_soon: "جزئیات بسته به زودی ارائه می‌شود. برای قیمت سفارشی با ما تماس بگیرید.",
        cost_estimator: "تخمین‌گر هزینه", investment_visualization: "برآورد سرمایه‌گذاری",
        calculator_desc: "از الگوریتم دقیق ما برای تخمین منابع مورد نیاز پروژه خود استفاده کنید. تمامی تخمین‌ها پس از بررسی نهایی تایید می‌شوند.",
        estimated_total: "کل تخمینی", estimated_delivery: "زمان تحویل تخمینی (روز)",
        project_stream: "نوع پروژه", temporal_duration: "مدت زمان",
        structural_complexity: "پیچیدگی ساختاری", level: "سطح",
        accelerated_deployment: "تحویل فوری", fast_turnaround_desc: "۳۰٪ زمان تحویل سریع‌تر",
        initiate_quote: "شروع دریافت پیش‌فاکتور", stream_animation: "انیمیشن", stream_explainer: "ویدیوی توضیحی", stream_3d: "انیمیشن سه‌بعدی",
        review_sub: "نظرات مشتریان", review_title: "رضایت‌نامه‌ها", write_review: "ثبت نظر",
        live_verification: "تایید رسمی کسب‌وکار", google_reviews_title: "نظرات گوگل اسموت‌پیکسل",
        directions: "مسیریابی", save: "ذخیره", telegram: "تلگرام", open_24_hours: "۲۴ ساعته باز است",
        write_review_btn: "ثبت نظر", google_reviews_count: "نظرات گوگل",
        posting_publicly: "انتشار عمومی در گوگل", share_experience_placeholder: "جزئیات تجربه خود را در این مکان به اشتراک بگذارید",
        change_photo: "تغییر عکس", add_photo_video: "افزودن عکس و ویدیو",
        reviewer_details_title: "جزئیات هویت شما", your_name_placeholder: "نام شما (الزامی) *",
        company_project_placeholder: "شرکت / پروژه (اختیاری)", website_url_placeholder: "آدرس وب‌سایت (اختیاری)",
        cancel: "لغو", post: "ارسال", posting: "در حال ارسال...", website_review: "نظرات وب‌سایت", google_review: "نظرات گوگل",
        review_submitted_title: "نظر ثبت شد!", review_submitted_desc: "نظر شما با موفقیت ثبت شد و برای تایید ارسال گردید. با تشکر از بازخورد شما!",
        helpful: "مفید", less: " کمتر", more: " بیشتر", local_guide: "راهنمای محلی",
        freelance_promo: "سلام👋 من برای پروژه‌های فریلنسری آماده‌ام", quick_response: "برای پاسخ سریع:",
                rating_terrible: "خیلی بد", rating_poor: "بد", rating_average: "متوسط", rating_good: "خوب", rating_excellent: "عالی",
        studio_subtitle: "استودیو انیمیشن و موشن گرافیک",
        your_name: "نام شما *",
        website_link_optional: "لینک وب‌سایت (اختیاری)",
        social_profile_optional: "پروفایل شبکه اجتماعی (اختیاری)",
        profile_photo_optional: "عکس پروفایل (اختیاری)",
        click_stars_to_rate: "برای امتیازدهی روی ستاره‌ها کلیک کنید",
        review_deck_desc: "این نظر در بخش اسلایدر صفحه اصلی ما نمایش داده خواهد شد",
        submit_website_testimonial: "ثبت نظر برای وب‌سایت",
        enter_name_placeholder: "نام خود را وارد کنید (به عنوان مثال علی)",
        describe_project_placeholder: "پروژه خلاقانه خود با SmooothPixel، کیفیت کار و سرعت تحویل را توصیف کنید...",
        company_name_placeholder: "به عنوان مثال شرکت اسموت‌پیکسل",
        tier_basic: "پایه",
        tier_standard: "استاندارد",
        tier_premium: "ویژه"
    },
    ps: {
        home: "کور", services: "خدمتونه", portfolio: "پروژې",
        pricing: "نرخونه", contact: "اړیکه", lets_talk: "خبرې وکړو",
        banner_title: "له یوې ساده نظریې څخه تر جذاب ویډیو پورې",
        banner_subtitle: "د نظرونو ژوندي کولو ۱۵ کاله. زه د موشن ګرافیک، ۲ډي انیمیشن، او تشریحي ویډیوګانو له لارې د برانډونو سره د نه هیریدونکو کیسو په جوړولو کې مرسته کوم.",
        hire_me: "همدا اوس ما استخدام کړئ", watch_showreel: "شوریل وګورئ",
        services_sub: "خدمتونه", services_title: "غوره تخلیقي حلونه",
        explore: "لټول",
        about_sub: "تخلیقي کیسه لیکنه", about_title: "د داسې خوځښت رامینځته کول چې ستاسو برانډ تعریفوي",
        about_p1: "په Smoooth Pixel کې، موږ یوازې انیمیشن نه کوو؛ موږ نظرونو ته ژوند ورکوو. د ارشد موشن ګرافیک متخصص په توګه، زه د صنعت ۱۵ کلنه مخکښه تجربه د پرمختللي بصري ټیکنالوژۍ سره یوځای کوم.",
        about_p2: "زموږ فلسفه ساده ده: په حرکت کې ښکلا. که دا د لوړ کیفیت کارپوریټ پیژندنه وي، پیچلي ۳ډي تخنیکي لیدونه وي، یا ګړندي ټولنیز رسنۍ وي، موږ په زړه پورې پایلې وړاندې کوو.",
        view_showreel: "شوریل وګورئ",
        years_experience: "د تجربې کلونه", projects_done: "بشپړې شوې پروژې",
        clients: "پیرودونکي", satisfied_globally: "په ټوله نړۍ کې خوښ پیرودونکي",
        facts_sub: "وسایل او سافټویرونه", facts_title: "هغه سافټویرونه چې موږ ورباندې مسلط یو",
        team_sub: "تخلیقي ټیم", team_title: "د حرکت له جوړونکو سره لیدنه وکړئ",
        view_resume: "رزومه وګورئ",
        contact_title: "اړیکه ونیسئ",
        contact_name: "نوم", contact_email: "بریښنالیک*", contact_phone: "تلیفون",
        contact_telegram: "ټیلیګرام @username", contact_message: "د پروژې په اړه ووایاست *",
        contact_submit: "اړیکه ونیسئ", contact_sending: "د لیږلو په حال کې...",
        ready_for_work: "کار ته چمتو",
        years_expert: "کلونه\nتجربه",
        senior_expert: "د موشن ګرافیک او ۳ډي لیدونو ارشد متخصص",
        official_email: "رسمي بریښنالیک", telegram_support: "ټیلیګرام ملاتړ",
        portfolio_sub: "غوره شوي کارونه", portfolio_title: "زموږ وروستۍ پروژې",
        showreel_sub: "د پردې تر شا", showreel_title: "زموږ شوریل وګورئ",
        pricing_sub: "پکیجونه", pricing_title: "ساده او روښانه نرخونه",
        copyright: "ټول حقونه خوندي دي",
        back_to_roster: "بېرته لیست ته", key_proficiencies: "مهم مهارتونه",
        work_history: "د کار تاریخ", my_expertise: "زما تخصص",
        academic_background: "علمي مخینه", education: "زده کړې",
        no_timeline_entries: "تر اوسه هیڅ ثبت شوی نه دی.",
        loading_profile: "د تخلیقي پروفایل د پورته کولو په حال کې...", profile_error: "پروفایل کې تېروتنه",
        back_to_home: "بېرته کور پاڼې ته",
        creative_designer_bio: "تخلیقي ډیزاینر او د حرکت جوړونکی، چې په زړه پورې سینمایي تجارب ډیزاین کوي.",
        
        // New Keys
        work: "پروژې", team: "زموږ ټیم", reviews: "بیاکتنې", price_calculator: "د بیې حسابوونکی", about: "زموږ په اړه",
        animation_motion: "انیمیشن او حرکت", saas_explainers: "SaaS او تشریحي ويډیوګانې", video_production: "ویډیو جوړول",
        estimate_budget: "بودجه اټکل کړئ", pricing_packages: "د بیو کڅوړې", overview: "عمومي کتنه",
        free_consultation: "وړیا مشوره", our_expertise: "زموږ مهارتونه",
        expertise_desc: "د هوښیارو برانډونو لپاره ۳ډي انیمیشن، SaaS تشریحات، او سینمایي ویډیو تولید.",
        all: "ټول", view_all_projects: "ټولې پروژې وګورئ", order_now: "همدا اوس امر وکړئ",
        loading_packages: "د غوره کڅوړو د پورته کولو په حال کې...", no_packages_available: "تر اوسه هیڅ ډول کڅوړې نشته.",
        details_coming_soon: "د کڅوړې معلومات به ډیر ژر خپاره شي. د ځانګړي نرخ لپاره اړیکه ونیسئ.",
        cost_estimator: "د لګښت اټکلوونکی", investment_visualization: "د لګښت لیدلوری",
        calculator_desc: "ستاسو د تخلیقي پروژې لپاره د اړتیا وړ سرچینو اټکل کولو لپاره زموږ دقیق الګوریتم وکاروئ. ټول اټکلونه د وروستي بیاکتنې تابع دي.",
        estimated_total: "اټکل شوی ټول لګښت", estimated_delivery: "اټکل شوې تحویلۍ (ورځې)",
        project_stream: "د پروژې ډول", temporal_duration: "وخت او موده",
        structural_complexity: "د جوړښت پیچلتیا", level: "کچه",
        accelerated_deployment: "ګړندی تحویل او تسلیمي", fast_turnaround_desc: "۳۰٪ ګړندۍ کاري پروسه",
        initiate_quote: "د بشپړ نرخ غوښتنه", stream_animation: "انیمیشن", stream_explainer: "تشریحي ویډیو", stream_3d: "۳ډي انیمیشن",
        review_sub: "د پیرودونکو احساسات", review_title: "د پیرودونکو نظرونه", write_review: "نظر لیکل",
        live_verification: "د سوداګرۍ ژوندۍ تایید", google_reviews_title: "د SmooothPixel ګوګل بیاکتنې",
        directions: "لارښوونې", save: "خوندي کول", telegram: "ټیلیګرام", open_24_hours: "۲۴ ساعته خلاص دی",
        write_review_btn: "نظر ورکول", google_reviews_count: "ګوګل بیاکتنې",
        posting_publicly: "په ګوګل کې عمومي خپریدل", share_experience_placeholder: "په دې ځای کې د خپلې تجربې په اړه ولیکئ",
        change_photo: "د عکس بدلول", add_photo_video: "عکس یا ویډیو زیاته کړئ",
        reviewer_details_title: "ستاسو معلومات", your_name_placeholder: "ستاسو نوم (لازمي) *",
        company_project_placeholder: "کمپنۍ / پروژه (اختياري)", website_url_placeholder: "د ویب پاڼې ادرس (اختياري)",
        cancel: "بندول", post: "خپرول", posting: "د خپرېدو په حال کې...", website_review: "د ویب پاڼې نظر", google_review: "ګوګل نظر",
        review_submitted_title: "نظر ورسپارل شو!", review_submitted_desc: "ستاسو نظر په بریالیتوب سره ثبت شو او د کتنې لپاره واستول شو. ستاسو له همکارۍ مننه!",
        helpful: "ګټور", less: " لږ", more: " ډیر", local_guide: "ملا وتړونکی",
        freelance_promo: "سلام👋 زه د فریلنس کارونو لپاره چمتو یم", quick_response: "د ګړندي ځواب لپاره:",
                rating_terrible: "خورا خراب", rating_poor: "خراب", rating_average: "اوسط", rating_good: "ښه", rating_excellent: "غوره",
        studio_subtitle: "د انیمیشن او موشن ګرافیک سټوډیو",
        your_name: "ستاسو نوم *",
        website_link_optional: "د ویب پاڼې لینک (اختياري)",
        social_profile_optional: "ټولنیز پروفایل (اختياري)",
        profile_photo_optional: "د پروفایل عکس (اختياري)",
        click_stars_to_rate: "د درجه بندي لپاره په ستورو کلیک وکړئ",
        review_deck_desc: "دا نظر به زموږ د کور پاڼې په سلایډونو کې ښکاره شي",
        submit_website_testimonial: "د ویب پاڼې لپاره نظر ثبتول",
        enter_name_placeholder: "خپل نوم ولیکئ (مثلا احمد)",
        describe_project_placeholder: "د SmooothPixel سره خپله تخلیقي پروژه، د کار کیفیت او د تحویل سرعت بیان کړئ...",
        company_name_placeholder: "مثلا د اسموت پکسل شرکت",
        tier_basic: "اساسي",
        tier_standard: "معیاري",
        tier_premium: "غوره"
    }
};

interface LanguageContextType {
    currentLanguage: LanguageCode;
    setLanguage: (code: LanguageCode) => void;
    t: (key: string) => string;
    dir: 'ltr' | 'rtl';
    languages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [currentLanguage, setCurrentLanguage] = useState<LanguageCode>(() => {
        const saved = localStorage.getItem('sp_lang');
        return (saved as LanguageCode) || 'en';
    });

    const setLanguage = (code: LanguageCode) => {
        setCurrentLanguage(code);
        localStorage.setItem('sp_lang', code);
    };

    const activeLang = LANGUAGES.find(l => l.code === currentLanguage) || LANGUAGES[0];
    const dir = activeLang.dir;

    useEffect(() => {
        document.documentElement.dir = dir;
        document.documentElement.lang = currentLanguage;
    }, [dir, currentLanguage]);

    const t = (key: string): string => {
        return TRANSLATIONS[currentLanguage]?.[key] || TRANSLATIONS['en']?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, dir, languages: LANGUAGES }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
