import type { Language, LanguageCode } from './languageTypes';

export const LANGUAGES: Language[] = [
    { code: 'en', name: 'English', flag: '🇬🇧', dir: 'ltr' },
    { code: 'de', name: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
    { code: 'fr', name: 'Français', flag: '🇫🇷', dir: 'ltr' },
    { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
    { code: 'fa', name: 'فارسی', flag: '🇮🇷', dir: 'rtl' },
    { code: 'ps', name: 'پښتو', flag: '🇦🇫', dir: 'rtl' }
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
    en: {
        home: "Home", services: "Services", portfolio: "Portfolio",
        pricing: "Pricing", contact: "Contact", lets_talk: "Let's Talk",
        banner_title: "From Simple Idea to Captivating Video",
        banner_subtitle: "15 years of bringing ideas to life. I help brands tell unforgettable stories through motion graphics, 2D animation, and explainer videos.",
        hire_me: "Hire Me Now", watch_showreel: "Watch Showreel",
        services_sub: "Services", services_title: "Premium Creative Solutions",
        explore: "Explore",
        about_sub: "Creative Storytelling", about_title: "Crafting Motion that Defines Your Brand",
        about_p1: "At Smoooth Pixel, we don't just animate; we breathe life into ideas. As a senior motion graphics specialist, I blend 15 years of industry-leading expertise with cutting-edge visual technology to create cinematic experiences that resonate globally.",
        about_p2: "Our philosophy is simple: Elegance in Motion. Whether it's high-end corporate identities, complex 3D technical visualizations, or fast-paced social media campaigns, we deliver pixel-perfect results that leave a lasting impact.",
        view_showreel: "View Showreel",
        years_experience: "Years Experience", projects_done: "Projects Done",
        clients: "Clients", satisfied_globally: "Satisfied Globally",
        facts_sub: "Tools & Software", facts_title: "Software We Master",
        team_sub: "Creative Collective", team_title: "Meet the Architects of Motion",
        view_resume: "View Resume",
        contact_title: "Contact Me",
        contact_name: "Name", contact_email: "Email*", contact_phone: "Phone",
        contact_telegram: "Telegram @username", contact_message: "Tell Us About Project *",
        contact_submit: "Get in Touch", contact_sending: "Sending…",
        ready_for_work: "Ready for work",
        years_expert: "YEARS\nEXPERT",
        senior_expert: "Senior Motion Graphics & 3D Visualization Expert",
        official_email: "Official Email",
        telegram_support: "Telegram Support",
        portfolio_sub: "Selected Works", portfolio_title: "Our Latest Projects",
        showreel_sub: "Behind the Scenes", showreel_title: "Watch Our Showreel",
        pricing_sub: "Packages", pricing_title: "Simple Transparent Pricing",
        copyright: "All Rights Reserved",
        back_to_roster: "Back to Roster", key_proficiencies: "Key Proficiencies",
        work_history: "Work History", my_expertise: "My Expertise",
        academic_background: "Academic Background", education: "Education",
        no_timeline_entries: "No entries listed yet.",
        loading_profile: "Loading creative profile...", profile_error: "Profile Error",
        back_to_home: "Back to Home",
        creative_designer_bio: "Creative designer and crucial architect of motion, styling stunning cinematic experiences.",
        work: "Work", team: "Team", reviews: "Reviews", price_calculator: "Price Calculator", about: "About",
        animation_motion: "Animation & Motion", saas_explainers: "SaaS & Explainers", video_production: "Video Production",
        estimate_budget: "Estimate budget", pricing_packages: "Pricing packages", overview: "Overview",
        our_expertise: "Our expertise", motion_graphics_desc: "3D, VFX & motion graphics",
        product_demos_desc: "Product demos & walkthroughs", edit_grade_delivery_desc: "Edit, grade & delivery",
        selected_projects_desc: "Selected client projects", watch_best_cuts_desc: "Watch our best cuts",
        cost_tool_desc: "Interactive project cost tool", fixed_plans_desc: "Fixed plans & deliverables",
        showreel: "Showreel", portfolio: "Portfolio",
        free_consultation: "Free consultation", our_expertise: "Our expertise",
        expertise_desc: "Premium 3D animation, SaaS explainers, and cinematic video production for ambitious brands.",
        all: "All", view_all_projects: "View All Projects", order_now: "Order Now",
        loading_packages: "Loading premium packages...", no_packages_available: "No pricing packages are currently available.",
        details_coming_soon: "Package details coming soon. Contact us for a custom quote.",
        cost_estimator: "Cost Estimator", investment_visualization: "Investment Visualization",
        calculator_desc: "Use our high-precision algorithm to estimate the resource allocation for your creative project. All estimates are subject to final creative brief analysis.",
        estimated_total: "Estimated Total", estimated_delivery: "Est. Delivery (Days)",
        project_stream: "Project Stream", temporal_duration: "Temporal Duration",
        structural_complexity: "Structural Complexity", level: "Level",
        accelerated_deployment: "Accelerated Deployment", fast_turnaround_desc: "30% faster turnaround",
        initiate_quote: "Initiate Full Quote", stream_animation: "Animation", stream_explainer: "Explainer", stream_3d: "3D Animation",
        review_sub: "Client Sentiment", review_title: "Client Testimonials", write_review: "Write a Review",
        live_verification: "Live Business Verification", google_reviews_title: "SmooothPixel Google Reviews",
        directions: "Directions", save: "Save", telegram: "Telegram", open_24_hours: "Open 24 hours",
        write_review_btn: "Write a review", google_reviews_count: "Google reviews",
        posting_publicly: "Posting publicly across Google", share_experience_placeholder: "Share details of your own experience at this place",
        change_photo: "Change Photo", add_photo_video: "Add photos and videos",
        reviewer_details_title: "Your Reviewer Details", your_name_placeholder: "Your Name (Required) *",
        company_project_placeholder: "Company / Project (Optional)", website_url_placeholder: "Website URL (Optional)",
        cancel: "Cancel", post: "Post", posting: "Posting...", website_review: "Website Review", google_review: "Google Review",
        review_submitted_title: "Review Submitted!", review_submitted_desc: "Your review was submitted successfully and sent to moderation. Thank you for your feedback!",
        helpful: "Helpful", less: " Less", more: " More", local_guide: "Local Guide",
        freelance_promo: "Hello👋 i'm available for freelance work", quick_response: "For quick response:",
        rating_terrible: "Terrible", rating_poor: "Poor", rating_average: "Average", rating_good: "Good", rating_excellent: "Excellent",
        studio_subtitle: "Animation & Motion Graphics Studio",
        your_name: "Your Name *",
        website_link_optional: "Website Link (Optional)",
        social_profile_optional: "Social Profile (Optional)",
        profile_photo_optional: "Profile Photo (Optional)",
        click_stars_to_rate: "Click stars to rate",
        review_deck_desc: "This review will appear on our home page slide deck",
        submit_website_testimonial: "Submit Website Testimonial",
        enter_name_placeholder: "Enter your name (e.g. Felix)",
        describe_project_placeholder: "Describe your creative project with SmooothPixel, quality of work, and delivery speed...",
        company_name_placeholder: "e.g. SmooothPixel Co.",
        tier_basic: "Basic",
        tier_standard: "Standard",
        tier_premium: "Premium"
    },
    // Pashto (ps) — partial translation. Missing keys fall back to English
    // in LanguageContext.tsx via the `t()` helper, so this is intentional.
    ps: {
        home: "کور", services: "خدمات", contact: "اړیکه", lets_talk: "خبریات",
        projects_done: "بشپړې شوې پروژې",
        clients: "پیرودونکي", satisfied_globally: "په ټوله نړۍ کې خوښ پیرودونکي",
        facts_sub: "وسایل او سافټویرونه", facts_title: "هغه سافټویرونه چې موږ ورباندې مسلط یو",
        team_sub: "تخلیقي ټیم", team_title: "د حرکت له جوړونکو سره لیدنه وکړئ",
        view_resume: "رزومه وګورئ",
        contact_title: "اړیکه ونیسئ",
        contact_name: "نوم", contact_email: "بریښنالیک*", contact_phone: "تلیفون",
        contact_telegram: "ټیلیګرام @username", contact_message: "د پروژې په اړه ووایاست *",
        contact_submit: "اړیکه ونیسئ", contact_sending: "د لیږلو په حال کې...",
        ready_for_work: "کار ته چمتو",
        years_expert: "کلونه\nتجربه",
        senior_expert: "د موشن ګرافیک او ۳ډي لیدونو ارشد متخصص",
        official_email: "رسمي بریښنالیک", telegram_support: "ټیلیګرام ملاتړ",
        portfolio_sub: "غوره شوي کارونه", portfolio_title: "زموږ وروستۍ پروژې",
        showreel_sub: "د پردې تر شا", showreel_title: "زموږ شوریل وګورئ",
        pricing_sub: "پکیجونه", pricing_title: "ساده او روښانه نرخونه",
        copyright: "ټول حقونه خوندي دي",
        back_to_roster: "بېرته لیست ته", key_proficiencies: "مهم مهارتونه",
        work_history: "د کار تاریخ", my_expertise: "زما تخصص",
        academic_background: "علمي مخینه", education: "زده کړې",
        no_timeline_entries: "تر اوسه هیڅ ثبت شوی نه دی.",
        loading_profile: "د تخلیقي پروفایل د پورته کولو په حال کې...", profile_error: "پروفایل کې تېروتنه",
        back_to_home: "بېرته کور پاڼې ته",
        creative_designer_bio: "تخلیقي ډیزاینر او د حرکت جوړونکی، چې په زړه پورې سینمایي تجارب ډیزاین کوي.",
        work: "پروژې", team: "زموږ ټیم", reviews: "بیاکتنې", price_calculator: "د بیې حسابوونکی", about: "زموږ په اړه",
        animation_motion: "انیمیشن او حرکت", saas_explainers: "SaaS او تشریحي ويډیوګانې", video_production: "ویډیو جوړول",
        estimate_budget: "بودجه اټکل کړئ", pricing_packages: "د بیو کڅوړې", overview: "عمومي کتنه",
        our_expertise: "زموږ تخصص", motion_graphics_desc: "۳ډي، ویفیکس او موشن ګرافیک",
        product_demos_desc: "د محصول تعارف او لارښوونې", edit_grade_delivery_desc: "د ویرایش، رنګینګ او تحویل",
        selected_projects_desc: "غوره شوي پیرودونکي پروژې", watch_best_cuts_desc: "زموږ غوره کټونه وګورئ",
        cost_tool_desc: "د پروژې لګښت اټکلوونکی وسیله", fixed_plans_desc: "ثابت پلانونه او تحویل",
        showreel: "شوریل", portfolio: "پورټفولیو",
        free_consultation: "وړیا مشوره", our_expertise: "زموږ مهارتونه",
        expertise_desc: "د هوښیارو برانډونو لپاره ۳ډي انیمیشن، SaaS تشریحات، او سینمایي ویډیو تولید.",
        all: "ټول", view_all_projects: "ټولې پروژې وګورئ", order_now: "همدا اوس امر وکړئ",
        loading_packages: "د غوره کڅوړو د پورته کولو په حال کې...", no_packages_available: "تر اوسه هیڅ ډول کڅوړې نشته.",
        details_coming_soon: "د کڅوړې معلومات به ډیر ژر خپاره شي. د ځانګړي نرخ لپاره اړیکه ونیسئ.",
        cost_estimator: "د لګښت اټکلوونکی", investment_visualization: "د لګښت لیدلوری",
        calculator_desc: "ستاسو د تخلیقي پروژې لپاره د اړتیا وړ سرچینو اټکل کولو لپاره زموږ دقیق الګوریتم وکاروئ. ټول اټکلونه د وروستي بیاکتنې تابع دي.",
        estimated_total: "اټکل شوی ټول لګښت", estimated_delivery: "اټکل شوې تحویلۍ (ورځې)",
        project_stream: "د پروژې ډول", temporal_duration: "وخت او موده",
        structural_complexity: "د جوړښت پیچلتیا", level: "کچه",
        accelerated_deployment: "ګړندی تحویل او تسلیمي", fast_turnaround_desc: "۳۰٪ ګړندۍ کاري پروسه",
        initiate_quote: "د بشپړ نرخ غوښتنه", stream_animation: "انیمیشن", stream_explainer: "تشریحي ویډیو", stream_3d: "۳ډي انیمیشن",
        review_sub: "د پیرودونکو احساسات", review_title: "د پیرودونکو نظرونه", write_review: "نظر لیکل",
        live_verification: "د سوداګرۍ ژوندۍ تایید", google_reviews_title: "د SmooothPixel ګوګل بیاکتنې",
        directions: "لارښوونې", save: "خوندي کول", telegram: "ټیلیګرام", open_24_hours: "۲۴ ساعته خلاص دی",
        write_review_btn: "نظر ورکول", google_reviews_count: "ګوګل بیاکتنې",
        posting_publicly: "په ګوګل کې عمومي خپریدل", share_experience_placeholder: "په دې ځای کې د خپلې تجربې په اړه ولیکئ",
        change_photo: "د عکس بدلول", add_photo_video: "عکس یا ویډیو زیاته کړئ",
        reviewer_details_title: "ستاسو معلومات", your_name_placeholder: "ستاسو نوم (لازمي) *",
        company_project_placeholder: "کمپنۍ / پروژه (اختياري)", website_url_placeholder: "د ویب پاڼې ادرس (اختياري)",
        cancel: "بندول", post: "خپرول", posting: "د خپرېدو په حال کې...", website_review: "د ویب پاڼې نظر", google_review: "ګوګل نظر",
        review_submitted_title: "نظر ورسپارل شو!", review_submitted_desc: "ستاسو نظر په بریالیتوب سره ثبت شو او د کتنې لپاره واستول شو. ستاسو له همکارۍ مننه!",
        helpful: "ګټور", less: " لږ", more: " ډیر", local_guide: "ملا وتړونکی",
        freelance_promo: "سلام👋 زه د فریلنس کارونو لپاره چمتو یم", quick_response: "د ګړندي ځواب لپاره:",
        rating_terrible: "خورا خراب", rating_poor: "خراب", rating_average: "اوسط", rating_good: "ښه", rating_excellent: "غوره",
        studio_subtitle: "د انیمیشن او موشن ګرافیک سټوډیو",
        your_name: "ستاسو نوم *",
        website_link_optional: "د ویب پاڼې لینک (اختياري)",
        social_profile_optional: "ټولنیز پروفایل (اختياري)",
        profile_photo_optional: "د پروفایل عکس (اختياري)",
        click_stars_to_rate: "د درجه بندي لپاره په ستورو کلیک وکړئ",
        review_deck_desc: "دا نظر به زموږ د کور پاڼې په سلایډونو کې ښکاره شي",
        submit_website_testimonial: "د ویب پاڼې لپاره نظر ثبتول",
        enter_name_placeholder: "خپل نوم ولیکئ (مثلا احمد)",
        describe_project_placeholder: "د SmooothPixel سره خپله تخلیقي پروژه، د کار کیفیت او د تحویل سرعت بیان کړئ...",
        company_name_placeholder: "مثلا د اسموت پکسل شرکت",
        tier_basic: "اساسي",
        tier_standard: "معیاري",
        tier_premium: "غوره"
    },
    de: {
        home: "Startseite", services: "Dienstleistungen", portfolio: "Portfolio",
        pricing: "Preise", contact: "Kontakt", lets_talk: "Sprechen wir",
        banner_title: "Von der einfachen Idee zum faszinierenden Video",
        banner_subtitle: "15 Jahre, die Ideen zum Leben erwecken. Ich helfe Marken, unvergessliche Geschichten durch Motion Graphics, 2D-Animation und Erklärvideos zu erzählen.",
        hire_me: "Jetzt anheuern", watch_showreel: "Showreel ansehen",
        services_sub: "Dienstleistungen", services_title: "Premium-Kreativlösungen",
        explore: "Erkunden",
        about_sub: "Kreatives Storytelling", about_title: "Motion gestalten, das Ihre Marke definiert",
        about_p1: "Bei Smoooth Pixel animieren wir nicht nur; wir verleihen Ideen Leben. Als erfahrener Motion-Graphics-Spezialist verbinde ich 15 Jahre branchenführendes Fachwissen mit modernster Visualisierungstechnologie, um kinematische Erlebnisse zu schaffen, die global resonieren.",
        about_p2: "Unsere Philosophie ist einfach: Eleganz in Bewegung. Ob hochwertige Unternehmensidentitäten, komplexe 3D-technische Visualisierungen oder schnelllebige Social-Media-Kampagnen – wir liefern pixelgenaue Ergebnisse mit dauerhafter Wirkung.",
        view_showreel: "Showreel ansehen",
        years_experience: "Jahre Erfahrung", projects_done: "Abgeschlossene Projekte",
        clients: "Kunden", satisfied_globally: "Global zufrieden",
        facts_sub: "Werkzeuge & Software", facts_title: "Software, die wir beherrschen",
        team_sub: "Kreatives Kollektiv", team_title: "Treffen Sie die Architekten der Bewegung",
        view_resume: "Lebenslauf ansehen",
        contact_title: "Kontakt aufnehmen",
        contact_name: "Name", contact_email: "E-Mail*", contact_phone: "Telefon",
        contact_telegram: "Telegram @username", contact_message: "Erzählen Sie uns von Ihrem Projekt *",
        contact_submit: "Kontakt aufnehmen", contact_sending: "Wird gesendet…",
        ready_for_work: "Bereit für Arbeit",
        years_expert: "JAHRE\nERFAHRUNG",
        senior_expert: "Senior Motion Graphics & 3D-Visualisierungsexperte",
        official_email: "Offizielle E-Mail",
        telegram_support: "Telegram-Support",
        portfolio_sub: "Ausgewählte Werke", portfolio_title: "Unsere neuesten Projekte",
        showreel_sub: "Hinter den Kulissen", showreel_title: "Unser Showreel ansehen",
        pricing_sub: "Pakete", pricing_title: "Einfache transparente Preisgestaltung",
        copyright: "Alle Rechte vorbehalten",
        back_to_roster: "Zurück zur Liste", key_proficiencies: "Kernkompetenzen",
        work_history: "Berufserfahrung", my_expertise: "Meine Expertise",
        academic_background: "Akademischer Hintergrund", education: "Bildung",
        no_timeline_entries: "Noch keine Einträge.",
        loading_profile: "Kreatives Profil wird geladen...", profile_error: "Profilfehler",
        back_to_home: "Zurück zur Startseite",
        creative_designer_bio: "Kreativer Designer und wichtiger Architekt der Bewegung, der kinematische Erlebnisse gestaltet.",
        work: "Projekte", team: "Team", reviews: "Bewertungen", price_calculator: "Preisrechner", about: "Über uns",
        animation_motion: "Animation & Motion", saas_explainers: "SaaS & Erklärvideos", video_production: "Videoproduktion",
        estimate_budget: "Budget schätzen", pricing_packages: "Preispakete", overview: "Übersicht",
        our_expertise: "Unsere Expertise", motion_graphics_desc: "3D, VFX & Motion Graphics",
        product_demos_desc: "Produktdemos & Walkthroughs", edit_grade_delivery_desc: "Schnitt, Farbkorrektur & Lieferung",
        selected_projects_desc: "Ausgewählte Kundenprojekte", watch_best_cuts_desc: "Unsere besten Schnitte ansehen",
        cost_tool_desc: "Interaktives Projektkosten-Tool", fixed_plans_desc: "Fixe Pläne & Lieferungen",
        showreel: "Showreel", portfolio: "Portfolio",
        free_consultation: "Kostenlose Beratung", our_expertise: "Unsere Expertise",
        expertise_desc: "Premium-3D-Animation, SaaS-Erklärungen und kinematische Videoproduktion für ehrgeizige Marken.",
        all: "Alle", view_all_projects: "Alle Projekte ansehen", order_now: "Jetzt bestellen",
        loading_packages: "Premium-Pakete werden geladen...", no_packages_available: "Derzeit keine Preispakete verfügbar.",
        details_coming_soon: "Paketdetails kommen bald. Kontaktieren Sie uns für ein individuelles Angebot.",
        cost_estimator: "Kostenschätzer", investment_visualization: "Investitionsvisualisierung",
        calculator_desc: "Nutzen Sie unseren hochpräzisen Algorithmus, um die Ressourcenzuweisung für Ihr Kreativprojekt zu schätzen. Alle Schätzungen unterliegen der endgültigen kreativen BRIEF-Analyse.",
        estimated_total: "Geschätzte Gesamtkosten", estimated_delivery: "Geschätzte Lieferung (Tage)",
        project_stream: "Projekttyp", temporal_duration: "Zeitliche Dauer",
        structural_complexity: "Strukturelle Komplexität", level: "Stufe",
        accelerated_deployment: "Beschleunigte Bereitstellung", fast_turnaround_desc: "30% schnellerer Durchlauf",
        initiate_quote: "Vollständiges Angebot anfordern", stream_animation: "Animation", stream_explainer: "Erklärvideo", stream_3d: "3D-Animation",
        review_sub: "Kundenstimmen", review_title: "Kunden-Testimonials", write_review: "Bewertung schreiben",
        live_verification: "Live-Geschäftsverifizierung", google_reviews_title: "SmooothPixel Google-Bewertungen",
        directions: "Anfahrtsbeschreibung", save: "Speichern", telegram: "Telegram", open_24_hours: "24 Stunden geöffnet",
        write_review_btn: "Bewertung schreiben", google_reviews_count: "Google-Bewertungen",
        posting_publicly: "Öffentlich auf Google posten", share_experience_placeholder: "Teilen Sie Details Ihrer Erfahrung an diesem Ort",
        change_photo: "Foto ändern", add_photo_video: "Fotos und Videos hinzufügen",
        reviewer_details_title: "Ihre Bewerter-Details", your_name_placeholder: "Ihr Name (Erforderlich) *",
        company_project_placeholder: "Unternehmen / Projekt (Optional)", website_url_placeholder: "Website-URL (Optional)",
        cancel: "Abbrechen", post: "Posten", posting: "Wird gepostet...", website_review: "Website-Bewertung", google_review: "Google-Bewertung",
        review_submitted_title: "Bewertung gesendet!", review_submitted_desc: "Ihre Bewertung wurde erfolgreich gesendet und zur Moderation weitergeleitet. Vielen Dank für Ihr Feedback!",
        helpful: "Hilfreich", less: "Weniger", more: "Mehr", local_guide: "Lokaler Guide",
        freelance_promo: "Hallo👋 ich bin für Freelance-Arbeit verfügbar", quick_response: "Für schnelle Antwort:",
        rating_terrible: "Schrecklich", rating_poor: "Schlecht", rating_average: "Durchschnittlich", rating_good: "Gut", rating_excellent: "Ausgezeichnet",
        studio_subtitle: "Animations- & Motion-Graphics-Studio",
        your_name: "Ihr Name *",
        website_link_optional: "Website-Link (Optional)",
        social_profile_optional: "Soziales Profil (Optional)",
        profile_photo_optional: "Profilfoto (Optional)",
        click_stars_to_rate: "Klicken Sie auf Sterne zum Bewerten",
        review_deck_desc: "Diese Bewertung erscheint auf unserer Startseiten-Präsentation",
        submit_website_testimonial: "Website-Testimonial einreichen",
        enter_name_placeholder: "Geben Sie Ihren Namen ein (z.B. Felix)",
        describe_project_placeholder: "Beschreiben Sie Ihr kreatives Projekt mit SmooothPixel, Arbeitsqualität und Liefergeschwindigkeit...",
        company_name_placeholder: "z.B. SmooothPixel GmbH",
        tier_basic: "Basis",
        tier_standard: "Standard",
        tier_premium: "Premium"
    },
    fr: {
        home: "Accueil", services: "Services", portfolio: "Portfolio",
        pricing: "Tarifs", contact: "Contact", lets_talk: "Parlons-en",
        banner_title: "De l'idée simple à la vidéo captivante",
        banner_subtitle: "15 ans à donner vie aux idées. J'aide les marques à raconter des histoires inoubliables à travers le motion design, l'animation 2D et les vidéos explicatives.",
        hire_me: "Engagez-moi", watch_showreel: "Voir le showreel",
        services_sub: "Services", services_title: "Solutions créatives premium",
        explore: "Explorer",
        about_sub: "Storytelling créatif", about_title: "Créer le motion qui définit votre marque",
        about_p1: "Chez Smoooth Pixel, nous n'animons pas seulement; nous donnons vie aux idées. En tant que spécialiste senior du motion design, je combine 15 ans d'expertise de pointe avec une technologie visuelle de pointe pour créer des expériences cinématiques qui résonnent à l'échelle mondiale.",
        about_p2: "Notre philosophie est simple: l'élégance dans le mouvement. Qu'il s'agisse d'identités d'entreprise haut de gamme, de visualisations techniques 3D complexes ou de campagnes de médias sociaux dynamiques, nous livrons des résultats pixel-parfaits qui laissent une impression durable.",
        view_showreel: "Voir le showreel",
        years_experience: "Années d'expérience", projects_done: "Projets réalisés",
        clients: "Clients", satisfied_globally: "Satisfaits dans le monde",
        facts_sub: "Outils & Logiciels", facts_title: "Logiciels que nous maîtrisons",
        team_sub: "Collectif créatif", team_title: "Rencontrez les architectes du mouvement",
        view_resume: "Voir le CV",
        contact_title: "Me contacter",
        contact_name: "Nom", contact_email: "E-mail*", contact_phone: "Téléphone",
        contact_telegram: "Telegram @username", contact_message: "Parlez-nous de votre projet *",
        contact_submit: "Entrer en contact", contact_sending: "Envoi en cours…",
        ready_for_work: "Prêt à travailler",
        years_expert: "ANNÉES\nD'EXPERTISE",
        senior_expert: "Expert senior en motion design et visualisation 3D",
        official_email: "E-mail officiel",
        telegram_support: "Support Telegram",
        portfolio_sub: "Travaux sélectionnés", portfolio_title: "Nos derniers projets",
        showreel_sub: "Dans les coulisses", showreel_title: "Voir notre showreel",
        pricing_sub: "Forfaits", pricing_title: "Tarification simple et transparente",
        copyright: "Tous droits réservés",
        back_to_roster: "Retour à la liste", key_proficiencies: "Compétences clés",
        work_history: "Historique de travail", my_expertise: "Mon expertise",
        academic_background: "Formation académique", education: "Éducation",
        no_timeline_entries: "Aucune entrée pour le moment.",
        loading_profile: "Chargement du profil créatif...", profile_error: "Erreur de profil",
        back_to_home: "Retour à l'accueil",
        creative_designer_bio: "Designer créatif et architecte essentiel du mouvement, créant de superbes expériences cinématiques.",
        work: "Projets", team: "Équipe", reviews: "Avis", price_calculator: "Calculateur de prix", about: "À propos",
        animation_motion: "Animation & Motion", saas_explainers: "SaaS & Explicatifs", video_production: "Production vidéo",
        estimate_budget: "Estimer le budget", pricing_packages: "Forfaits tarifaires", overview: "Aperçu",
        our_expertise: "Notre expertise", motion_graphics_desc: "3D, VFX & motion design",
        product_demos_desc: "Démonstrations produit & visites guidées", edit_grade_delivery_desc: "Montage, étalonnage & livraison",
        selected_projects_desc: "Projets clients sélectionnés", watch_best_cuts_desc: "Voir nos meilleures coupes",
        cost_tool_desc: "Outil interactif de coût de projet", fixed_plans_desc: "Plans fixes & livrables",
        showreel: "Showreel", portfolio: "Portfolio",
        free_consultation: "Consultation gratuite", our_expertise: "Notre expertise",
        expertise_desc: "Animation 3D premium, explicatifs SaaS et production vidéo cinématique pour des marques ambitieuses.",
        all: "Tout", view_all_projects: "Voir tous les projets", order_now: "Commander maintenant",
        loading_packages: "Chargement des forfaits premium...", no_packages_available: "Aucun forfait tarifaire actuellement disponible.",
        details_coming_soon: "Détails du forfait à venir. Contactez-nous pour un devis personnalisé.",
        cost_estimator: "Estimateur de coût", investment_visualization: "Visualisation de l'investissement",
        calculator_desc: "Utilisez notre algorithme haute précision pour estimer l'allocation des ressources pour votre projet créatif. Toutes les estimations sont soumises à l'analyse finale du brief créatif.",
        estimated_total: "Total estimé", estimated_delivery: "Livraison estimée (Jours)",
        project_stream: "Type de projet", temporal_duration: "Durée temporelle",
        structural_complexity: "Complexité structurelle", level: "Niveau",
        accelerated_deployment: "Déploiement accéléré", fast_turnaround_desc: "30% plus rapide",
        initiate_quote: "Demander un devis complet", stream_animation: "Animation", stream_explainer: "Explicatif", stream_3d: "Animation 3D",
        review_sub: "Sentiment client", review_title: "Témoignages clients", write_review: "Écrire un avis",
        live_verification: "Vérification d'entreprise en direct", google_reviews_title: "Avis Google SmooothPixel",
        directions: "Itinéraire", save: "Enregistrer", telegram: "Telegram", open_24_hours: "Ouvert 24h/24",
        write_review_btn: "Écrire un avis", google_reviews_count: "Avis Google",
        posting_publicly: "Publication publiquement sur Google", share_experience_placeholder: "Partagez les détails de votre expérience dans ce lieu",
        change_photo: "Changer la photo", add_photo_video: "Ajouter des photos et vidéos",
        reviewer_details_title: "Vos coordonnées", your_name_placeholder: "Votre nom (Obligatoire) *",
        company_project_placeholder: "Entreprise / Projet (Optionnel)", website_url_placeholder: "URL du site web (Optionnel)",
        cancel: "Annuler", post: "Publier", posting: "Publication en cours...", website_review: "Avis du site", google_review: "Avis Google",
        review_submitted_title: "Avis envoyé!", review_submitted_desc: "Votre avis a été soumis avec succès et envoyé pour modération. Merci pour votre retour!",
        helpful: "Utile", less: "Moins", more: "Plus", local_guide: "Guide local",
        freelance_promo: "Bonjour👋 je suis disponible pour du travail freelance", quick_response: "Pour une réponse rapide:",
        rating_terrible: "Terrible", rating_poor: "Mauvais", rating_average: "Moyen", rating_good: "Bon", rating_excellent: "Excellent",
        studio_subtitle: "Studio d'animation et motion design",
        your_name: "Votre nom *",
        website_link_optional: "Lien du site web (Optionnel)",
        social_profile_optional: "Profil social (Optionnel)",
        profile_photo_optional: "Photo de profil (Optionnel)",
        click_stars_to_rate: "Cliquez sur les étoiles pour noter",
        review_deck_desc: "Cet avis apparaîtra sur le carrousel de notre page d'accueil",
        submit_website_testimonial: "Soumettre un témoignage",
        enter_name_placeholder: "Entrez votre nom (ex: Félix)",
        describe_project_placeholder: "Décrivez votre projet créatif avec SmooothPixel, la qualité du travail et la vitesse de livraison...",
        company_name_placeholder: "ex: SmooothPixel SARL",
        tier_basic: "Basique",
        tier_standard: "Standard",
        tier_premium: "Premium"
    },
    ar: {
        home: "الرئيسية", services: "الخدمات", portfolio: "المعرض",
        pricing: "الأسعار", contact: "اتصل بنا", lets_talk: "لنتحدث",
        banner_title: "من الفكرة البسيطة إلى الفيديو الجذاب",
        banner_subtitle: "15 عامًا في إحياء الأفكار. أساعد العلامات التجارية على سرد قصص لا تُنسى من خلال الرسوم المتحركة وتحرير الفيديو.",
        hire_me: "وظفني الآن", watch_showreel: "شاهد الأعمال",
        services_sub: "الخدمات", services_title: "حلول إبداعية مميزة",
        explore: "استكشف",
        about_sub: "السرد الإبداعي", about_title: "صنع الحركة التي تحدد علامتك التجارية",
        about_p1: "في Smoooth Pixel، لا نكتفي بالتحريك؛ نحن نحيي الأفكار. كمتخصص أول في الرسوم المتحركة، أجمع بين 15 عامًا من الخبرة القيادية مع أحدث التقنيات البصرية لخلق تجارب سينمائية يتردد صداه في جميع أنحاء العالم.",
        about_p2: "فلسفتنا بسيطة: الأناقة في الحركة. سواء كانت هويات شركات راقية أو تصورات تقنية ثلاثية الأبعاد معقدة أو حملات وسائط اجتماعية سريعة الوتيرة، نقدم نتائج مثالية تترك أثرًا دائمًا.",
        view_showreel: "شاهد الأعمال",
        years_experience: "سنوات الخبرة", projects_done: "المشاريع المنجزة",
        clients: "العملاء", satisfied_globally: "راضون في جميع أنحاء العالم",
        facts_sub: "الأدوات والبرمجيات", facts_title: "البرمجيات التي نتقنها",
        team_sub: "الفريق الإبداعي", team_title: "تعرف على صانعي الحركة",
        view_resume: "عرض السيرة الذاتية",
        contact_title: "تواصل معي",
        contact_name: "الاسم", contact_email: "البريد الإلكتروني*", contact_phone: "الهاتف",
        contact_telegram: "تيليجرام @username", contact_message: "أخبرنا عن مشروعك *",
        contact_submit: "تواصل معنا", contact_sending: "جارٍ الإرسال...",
        ready_for_work: "جاهز للعمل",
        years_expert: "سنوات\nالخبرة",
        senior_expert: "خبير أول في الرسوم المتحركة والتصور ثلاثي الأبعاد",
        official_email: "البريد الإلكتروني الرسمي",
        telegram_support: "دعم تيليجرام",
        portfolio_sub: "أعمال مختارة", portfolio_title: "آخر مشاريعنا",
        showreel_sub: "خلف الكواليس", showreel_title: "شاهد أعملنا",
        pricing_sub: "الباقات", pricing_title: "تسعير بسيط وشفاف",
        copyright: "جميع الحقوق محفوظة",
        back_to_roster: "العودة للقائمة", key_proficiencies: "المهارات الرئيسية",
        work_history: "تاريخ العمل", my_expertise: "خبرتي",
        academic_background: "الخلفية الأكاديمية", education: "التعليم",
        no_timeline_entries: "لا توجد إدخالات حتى الآن.",
        loading_profile: "جارٍ تحميل الملف الإبداعي...", profile_error: "خطأ في الملف",
        back_to_home: "العودة للرئيسية",
        creative_designer_bio: "مصمم إبداعي ومهندس أساسي للحركة، يصنع تجارب سينمائية مذهلة.",
        work: "الأعمال", team: "الفريق", reviews: "التقييمات", price_calculator: "حاسبة الأسعار", about: "من نحن",
        animation_motion: "الرسوم المتحركة", saas_explainers: "توضيحية SaaS", video_production: "إنتاج الفيديو",
        estimate_budget: "تقدير الميزانية", pricing_packages: "باقات الأسعار", overview: "نظرة عامة",
        our_expertise: "خبرتنا", motion_graphics_desc: "3D و VFX والرسوم المتحركة",
        product_demos_desc: "عروض المنتج والجولات", edit_grade_delivery_desc: "التحرير والتدرج والتسليم",
        selected_projects_desc: "مشاريع العملاء المختارة", watch_best_cuts_desc: "شاهد أفضل المقاطع",
        cost_tool_desc: "أداة تقدير تكلفة المشروع", fixed_plans_desc: "خطط ثابتة ومخرجات",
        showreel: "الأعمال", portfolio: "المعرض",
        free_consultation: "استشارة مجانية", our_expertise: "خبرتنا",
        expertise_desc: "رسوم ثلاثية الأبعاد متميزة وتوضيحية SaaS وإنتاج فيديو سينمائي للعلامات الطموحة.",
        all: "الكل", view_all_projects: "عرض كل المشاريع", order_now: "اطلب الآن",
        loading_packages: "جارٍ تحميل الباقات المتميزة...", no_packages_available: "لا توجد باقات أسعار متاحة حاليًا.",
        details_coming_soon: "ستأتي تفاصيل الباقة قريبًا. تواصل معنا للحصول على عرض سعر مخصص.",
        cost_estimator: "مقدر التكلفة", investment_visualization: "تصور الاستثمار",
        calculator_desc: "استخدم خوارزميتنا عالية الدقة لتقدير تخصيص الموارد لمشروعك الإبداعي. جميع التقديرات خاضعة للتحليل النهائي للوصف الإبداعي.",
        estimated_total: "الإجمالي المقدر", estimated_delivery: "التسليم المقدر (أيام)",
        project_stream: "نوع المشروع", temporal_duration: "المدة الزمنية",
        structural_complexity: "التعقيد البنيوي", level: "المستوى",
        accelerated_deployment: "النشر المتسارع", fast_turnaround_desc: "أسرع بنسبة 30%",
        initiate_quote: "طلب عرض سعر كامل", stream_animation: "الرسوم المتحركة", stream_explainer: "التوضيحية", stream_3d: "رسوم ثلاثية الأبعاد",
        review_sub: "آراء العملاء", review_title: "شهادات العملاء", write_review: "اكتب تقييمًا",
        live_verification: "التحقق الحي من الأعمال", google_reviews_title: "تقييمات Google لـ SmooothPixel",
        directions: "الاتجاهات", save: "حفظ", telegram: "تيليجرام", open_24_hours: "مفتوح 24 ساعة",
        write_review_btn: "اكتب تقييمًا", google_reviews_count: "تقييمات Google",
        posting_publicly: "النشر علنًا على Google", share_experience_placeholder: "شارك تفاصيل تجربتك في هذا المكان",
        change_photo: "تغيير الصورة", add_photo_video: "إضافة صور وفيديو",
        reviewer_details_title: "تفاصيل المقيّم", your_name_placeholder: "اسمك (مطلوب) *",
        company_project_placeholder: "الشركة / المشروع (اختياري)", website_url_placeholder: "رابط الموقع (اختياري)",
        cancel: "إلغاء", post: "نشر", posting: "جارٍ النشر...", website_review: "تقييم الموقع", google_review: "تقييم Google",
        review_submitted_title: "تم إرسال التقييم!", review_submitted_desc: "تم إرسال تقييمك بنجاح وإرساله للإشراف. شكرًا لملاحظاتك!",
        helpful: "مفيد", less: " أقل", more: " المزيد", local_guide: "مرشد محلي",
        freelance_promo: "مرحبًا👋 أنا متاح للعمل الحر", quick_response: "للرد السريع:",
        rating_terrible: "سيء جدًا", rating_poor: "سيء", rating_average: "مقبول", rating_good: "جيد", rating_excellent: "ممتاز",
        studio_subtitle: "استوديو الرسوم المتحركة والحركة",
        your_name: "اسمك *",
        website_link_optional: "رابط الموقع (اختياري)",
        social_profile_optional: "الملف الاجتماعي (اختياري)",
        profile_photo_optional: "صورة الملف الشخصي (اختياري)",
        click_stars_to_rate: "انقر على النجوم للتقييم",
        review_deck_desc: "سيظهر هذا التقييم في عرض الشرائح الرئيسي",
        submit_website_testimonial: "إرسال الشهادة",
        enter_name_placeholder: "أدخل اسمك (مثلاً: أحمد)",
        describe_project_placeholder: "صف مشروعك الإبداعي مع SmooothPixel، جودة العمل وسرعة التسليم...",
        company_name_placeholder: "مثل: شركة سموث بكسل",
        tier_basic: "أساسي",
        tier_standard: "قياسي",
        tier_premium: "مميز"
    },
    fa: {
        home: "خانه", services: "خدمات", portfolio: "نمونه کارها",
        pricing: "قیمت", contact: "تماس", lets_talk: "صحبت کنیم",
        banner_title: "از ایده ساده تا ویدیوی جذاب",
        banner_subtitle: "15 سال است که ایده‌ها را زنده می‌کنم. به برندها کمک می‌کنم تا داستان‌های فراموش‌نشدنی را از طریق گرافیک متحرک، انیمیشن 2D و ویدیوهای توضیحی روایت کنند.",
        hire_me: "همین الان استخدام کن", watch_showreel: "مشاهده کارها",
        services_sub: "خدمات", services_title: "راه‌حل‌های خلاقانه ممتاز",
        explore: "کاوش",
        about_sub: "داستان‌سرایی خلاقانه", about_title: "ساختن حرکتی که برند شما را تعریف می‌کند",
        about_p1: "در Smoooth Pixel، ما فقط متحرک‌سازی نمی‌کنیم؛ ما به ایده‌ها جان می‌دهیم. به عنوان یک متخصص ارشد گرافیک متحرک، 15 سال تخصص پیشرو در صنعت را با فناوری بصری پیشرفته ترکیب می‌کنم تا تجربیات سینمایی خلق کنم که در سراسر جهان طنین‌انداز باشد.",
        about_p2: "فلسفه ما ساده است: ظرافت در حرکت. چه هویت‌های شرکتی لوکس باشد، چه تصویرسازی‌های فنی سه‌بعدی پیچیده یا کمپین‌های سریع رسانه‌های اجتماعی، ما نتایج بی‌نقصی ارائه می‌دهیم که تأثیری ماندگار دارند.",
        view_showreel: "مشاهده کارها",
        years_experience: "سال تجربه", projects_done: "پروژه‌های انجام شده",
        clients: "مشتریان", satisfied_globally: "راضی در سراسر جهان",
        facts_sub: "ابزار و نرم‌افزار", facts_title: "نرم‌افزارهایی که تسلط داریم",
        team_sub: "تیم خلاق", team_title: "با معماران حرکت آشنا شوید",
        view_resume: "مشاهده رزومه",
        contact_title: "با من در تماس باشید",
        contact_name: "نام", contact_email: "ایمیل*", contact_phone: "تلفن",
        contact_telegram: "تلگرام @username", contact_message: "درباره پروژه‌تان بگویید *",
        contact_submit: "تماس بگیرید", contact_sending: "در حال ارسال...",
        ready_for_work: "آماده کار",
        years_expert: "سال\nتخصص",
        senior_expert: "متخصص ارشد گرافیک متحرک و تصویرسازی سه‌بعدی",
        official_email: "ایمیل رسمی",
        telegram_support: "پشتیبانی تلگرام",
        portfolio_sub: "کارهای منتخب", portfolio_title: "آخرین پروژه‌های ما",
        showreel_sub: "پشت صحنه", showreel_title: "کارهای ما را ببینید",
        pricing_sub: "پکیج‌ها", pricing_title: "قیمت‌گذاری ساده و شفاف",
        copyright: "تمام حقوق محفوظ است",
        back_to_roster: "بازگشت به لیست", key_proficiencies: "مهارت‌های کلیدی",
        work_history: "سوابق کاری", my_expertise: "تخصص من",
        academic_background: "پیشینه تحصیلی", education: "تحصیلات",
        no_timeline_entries: "هنوز هیچ موردی ثبت نشده.",
        loading_profile: "در حال بارگذاری پروفایل خلاقانه...", profile_error: "خطای پروفایل",
        back_to_home: "بازگشت به خانه",
        creative_designer_bio: "طراح خلاق و معمار اساسی حرکت، که تجربیات سینمایی خیره‌کننده را خلق می‌کند.",
        work: "کارها", team: "تیم", reviews: "نظرات", price_calculator: "ماشین حساب قیمت", about: "درباره ما",
        animation_motion: "انیمیشن و حرکت", saas_explainers: "SaaS و ویدیوهای توضیحی", video_production: "تولید ویدیو",
        estimate_budget: "برآورد بودجه", pricing_packages: "بسته‌های قیمت", overview: "نمای کلی",
        our_expertise: "تخصص ما", motion_graphics_desc: "3D، VFX و گرافیک متحرک",
        product_demos_desc: "دمو و راهنمای محصول", edit_grade_delivery_desc: "ویرایش، درجه‌بندی و تحویل",
        selected_projects_desc: "پروژه‌های منتخب مشتریان", watch_best_cuts_desc: "بهترین برش‌های ما را ببینید",
        cost_tool_desc: "ابزار تعاملی برآورد هزینه پروژه", fixed_plans_desc: "برنامه‌های ثابت و تحویلی",
        showreel: "نمایش کارها", portfolio: "نمونه کارها",
        free_consultation: "مشاوره رایگان", our_expertise: "تخصص ما",
        expertise_desc: "انیمیشن سه‌بعدی ممتاز، توضیحات SaaS و تولید ویدیوی سینمایی برای برندهای جاه‌طلب.",
        all: "همه", view_all_projects: "مشاهده همه پروژه‌ها", order_now: "همین الان سفارش دهید",
        loading_packages: "در حال بارگذاری بسته‌های ممتاز...", no_packages_available: "هیچ بسته قیمتی در حال حاضر موجود نیست.",
        details_coming_soon: "جزئیات بسته به زودی اعلام می‌شود. برای قیمت سفارشی با ما تماس بگیرید.",
        cost_estimator: "برآوردگر هزینه", investment_visualization: "تجسم سرمایه‌گذاری",
        calculator_desc: "از الگوریتم دقیق ما برای برآورد تخصیص منابع برای پروژه خلاقانه خود استفاده کنید. تمام برآوردها تابع تحلیل نهایی شرح خلاقانه هستند.",
        estimated_total: "مجموع برآوردی", estimated_delivery: "تحویل برآوردی (روز)",
        project_stream: "نوع پروژه", temporal_duration: "مدت زمان",
        structural_complexity: "پیچیدگی ساختاری", level: "سطح",
        accelerated_deployment: "تحویل شتاب‌دار", fast_turnaround_desc: "30% سریع‌تر",
        initiate_quote: "درخواست قیمت کامل", stream_animation: "انیمیشن", stream_explainer: "توضیحی", stream_3d: "انیمیشن سه‌بعدی",
        review_sub: "احساسات مشتری", review_title: "شهادات مشتریان", write_review: "نظر بنویسید",
        live_verification: "تأیید زنده کسب‌وکار", google_reviews_title: "نظرات گوگل SmooothPixel",
        directions: "مسیر", save: "ذخیره", telegram: "تلگرام", open_24_hours: "24 ساعته باز",
        write_review_btn: "نظر بنویسید", google_reviews_count: "نظرات گوگل",
        posting_publicly: "عمومی در گوگل پست می‌شود", share_experience_placeholder: "جزئیات تجربه خود در این مکان را به اشتراک بگذارید",
        change_photo: "تغییر عکس", add_photo_video: "عکس و ویدیو اضافه کنید",
        reviewer_details_title: "جزئیات نظردهنده", your_name_placeholder: "نام شما (الزامی) *",
        company_project_placeholder: "شرکت / پروژه (اختیاری)", website_url_placeholder: "آدرس وب‌سایت (اختیاری)",
        cancel: "لغو", post: "ارسال", posting: "در حال ارسال...", website_review: "نظر وب‌سایت", google_review: "نظر گوگل",
        review_submitted_title: "نظر ارسال شد!", review_submitted_desc: "نظر شما با موفقیت ارسال شد و برای بررسی ارسال گردید. از بازخورد شما سپاسگزاریم!",
        helpful: "مفید", less: " کمتر", more: " بیشتر", local_guide: "راهنمای محلی",
        freelance_promo: "سلام👋 برای کار فریلنسری آماده هستم", quick_response: "برای پاسخ سریع:",
        rating_terrible: "بسیار بد", rating_poor: "بد", rating_average: "متوسط", rating_good: "خوب", rating_excellent: "عالی",
        studio_subtitle: "استودیو انیمیشن و گرافیک متحرک",
        your_name: "نام شما *",
        website_link_optional: "لینک وب‌سایت (اختیاری)",
        social_profile_optional: "پروفایل اجتماعی (اختیاری)",
        profile_photo_optional: "عکس پروفایل (اختیاری)",
        click_stars_to_rate: "برای امتیازدهی روی ستاره‌ها کلیک کنید",
        review_deck_desc: "این نظر در اسلاید صفحه اصلی ما نمایش داده می‌شود",
        submit_website_testimonial: "ارسال شهادت وب‌سایت",
        enter_name_placeholder: "نام خود را وارد کنید (مثلاً: علی)",
        describe_project_placeholder: "پروژه خلاقانه خود با SmooothPixel، کیفیت کار و سرعت تحویل را توصیف کنید...",
        company_name_placeholder: "مثلاً: شرکت اسموث پیکسل",
        tier_basic: "پایه",
        tier_standard: "استاندارد",
        tier_premium: "ممتاز"
    }
};
