services:
  - type: web
    name: smooothpixel-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JWT_KEY
        value: A_Very_Complex_Secret_Key_That_Is_At_Least_32_Bytes_Long_123
      - key: JWT_ISSUER
        value: JwtIssuer
      - key: JWT_AUDIENCE
        value: JwtAudience
      - key: JWT_SUBJECT
        value: JwtSubject
      - key: DATABASE_URL
        fromDatabase:
          name: smooothpixel-db
          property: connectionString

databases:
  - name: smooothpixel-db
    databaseName: reactapi
    user: reactapi
    plan: free
