// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactApi.Infrastructer.Data;

#nullable disable

namespace ReactApi.Infrastructer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502095750_AddFrontendModels")]
    partial class AddFrontendModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "ListUser",
                            ClaimValue = "ListUser",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "CreateNewUser",
                            ClaimValue = "CreateNewUser",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "UpdateUser",
                            ClaimValue = "UpdateUser",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "UpdatePassword",
                            ClaimValue = "UpdatePassword",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "AssignRole",
                            ClaimValue = "AssignRole",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "ListRole",
                            ClaimValue = "ListRole",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "CreateNewRole",
                            ClaimValue = "CreateNewRole",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "UpdateRole",
                            ClaimValue = "UpdateRole",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "AssignPermissions",
                            ClaimValue = "AssignPermissions",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "ListCompanies",
                            ClaimValue = "ListCompanies",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "CreateCompany",
                            ClaimValue = "CreateCompany",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "EditCompany",
                            ClaimValue = "EditCompany",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "SearchCompany",
                            ClaimValue = "SearchCompany",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "ViewLicences",
                            ClaimValue = "ViewLicences",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "AddLicences",
                            ClaimValue = "AddLicences",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "EditLicences",
                            ClaimValue = "EditLicences",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "Licenceshistory",
                            ClaimValue = "Licenceshistory",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "Viewlicenceshistory",
                            ClaimValue = "Viewlicenceshistory",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "PrintJawaz",
                            ClaimValue = "PrintJawaz",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "Listcatagories",
                            ClaimValue = "Listcatagories",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "AddCatagory",
                            ClaimValue = "AddCatagory",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "EditCatagory",
                            ClaimValue = "EditCatagory",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b70a9c75-e14f-4180-8edb-8250ed8c8f8e",
                            RoleId = "5d7f49aa-de19-4b07-9fc0-6be07c56163d"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.ClientRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BudgetRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("ClientRequests");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.Companies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("English_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIN_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.LicenseCatagoies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fee")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("licenseCatagoies");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.Licenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("date");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Regno")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "CategoryId")
                        .IsUnique();

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.PortfolioProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProjectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("date");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Views")
                        .HasColumnType("int");

                    b.Property<string>("Visibility")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioProjects");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("date");

                    b.Property<string>("CtaLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtaText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroSubtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroVideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialBehance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialDribbble")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialInstagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialLinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("ReactApi.Domin.HistoryLicenesLogTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("date");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int>("LicensesId")
                        .HasColumnType("int");

                    b.Property<int>("PerviseState")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("LIcenesHistoryLog");
                });

            modelBuilder.Entity("ReactApi.Domin.identityModel.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5d7f49aa-de19-4b07-9fc0-6be07c56163d",
                            ConcurrencyStamp = "d727c9ac-042b-411f-8c9a-954fd9c237fd",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("ReactApi.Domin.identityModel.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b70a9c75-e14f-4180-8edb-8250ed8c8f8e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43f63b31-c198-4b83-82c4-fdde2a059352",
                            Email = "Admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB8QGw7QkaNCFGLogkDRfB8/0edzqYCmOAcFYoFmfvHX5fZStcwiO1I5xayDednEeg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a1e4c7b3-381e-4873-89bf-1470b34af7fc",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ReactApi.Domin.identityModel.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ReactApi.Domin.identityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ReactApi.Domin.identityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ReactApi.Domin.identityModel.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactApi.Domin.identityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ReactApi.Domin.identityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
