// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactApi.Infrastructer.Data;

#nullable disable

namespace ReactApi.Infrastructer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "ListUser",
                            ClaimValue = "ListUser",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "CreateNewUser",
                            ClaimValue = "CreateNewUser",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "UpdateUser",
                            ClaimValue = "UpdateUser",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "UpdatePassword",
                            ClaimValue = "UpdatePassword",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "AssignRole",
                            ClaimValue = "AssignRole",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "ListRole",
                            ClaimValue = "ListRole",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "CreateNewRole",
                            ClaimValue = "CreateNewRole",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "UpdateRole",
                            ClaimValue = "UpdateRole",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "AssignPermissions",
                            ClaimValue = "AssignPermissions",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "ListCompanies",
                            ClaimValue = "ListCompanies",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "CreateCompany",
                            ClaimValue = "CreateCompany",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "EditCompany",
                            ClaimValue = "EditCompany",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "SearchCompany",
                            ClaimValue = "SearchCompany",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "ViewLicences",
                            ClaimValue = "ViewLicences",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "AddLicences",
                            ClaimValue = "AddLicences",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "EditLicences",
                            ClaimValue = "EditLicences",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "Licenceshistory",
                            ClaimValue = "Licenceshistory",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "Viewlicenceshistory",
                            ClaimValue = "Viewlicenceshistory",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "PrintJawaz",
                            ClaimValue = "PrintJawaz",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "Listcatagories",
                            ClaimValue = "Listcatagories",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "AddCatagory",
                            ClaimValue = "AddCatagory",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "EditCatagory",
                            ClaimValue = "EditCatagory",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8179aa65-1499-441e-86f2-b717f57b331e",
                            RoleId = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.ClientRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BudgetRange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telegram")
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientRequests");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.PortfolioProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Challenge")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProjectDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solution")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Testimonial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumb")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbFull")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Views")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Visibility")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PortfolioProjects");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.Pricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ComplexityBasic")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ComplexityHigh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ComplexityMedium")
                        .HasColumnType("TEXT");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryDaysBasic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryDaysHigh")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryDaysMedium")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RateExplainer")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RateMotion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RateProduction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RateThreeD")
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UrgentMultiplier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pricings");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.ResumeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("ResumeEntries");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Project")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SocialLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainTitle")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiApiKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiSystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiWelcomeMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CtaLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("CtaText")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GalleryAutoplay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroSubtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTypedColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTypedText")
                        .HasColumnType("TEXT");

                    b.Property<double>("HeroVideoOpacity")
                        .HasColumnType("REAL");

                    b.Property<string>("HeroVideoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyEmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyEmailEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotifyTelegramBotToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyTelegramChatId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyTelegramEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialBehance")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialDribbble")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialInstagram")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialLinkedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.SocialAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SocialAccounts");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Linkedin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Twitter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProjectDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumb")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbFull")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.VideoCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VideoCategories");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.VisitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Createdby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CreatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Page")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Updatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UpdatedbyDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VisitorLogs");
                });

            modelBuilder.Entity("ReactApi.Domin.identityModel.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9a88e308-ee2f-4ece-a81e-6d60039ec2c4",
                            ConcurrencyStamp = "696a0335-74c3-4a55-a659-fb2c46565091",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("ReactApi.Domin.identityModel.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OtpAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtpCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8179aa65-1499-441e-86f2-b717f57b331e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a2891015-82b6-43e9-bac0-10701b247311",
                            Email = "Admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDd3xTbNyUlkpsemVhPPojgX5ww/CXCVRbO2ZYYJJ45NRAcCLSl+mGWKlgT/7Fhk9Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9fd6c95c-d1a5-4aa5-a64f-2567b1c34b3a",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ReactApi.Domin.identityModel.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ReactApi.Domin.identityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ReactApi.Domin.identityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ReactApi.Domin.identityModel.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactApi.Domin.identityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ReactApi.Domin.identityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.ResumeEntry", b =>
                {
                    b.HasOne("ReactApi.Domin.Commond_model.TeamMember", "TeamMember")
                        .WithMany("ResumeEntries")
                        .HasForeignKey("TeamMemberId");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.Video", b =>
                {
                    b.HasOne("ReactApi.Domin.Commond_model.VideoCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ReactApi.Domin.Commond_model.TeamMember", b =>
                {
                    b.Navigation("ResumeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
