CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "OtpCode" text,
    "OtpExpiry" timestamp with time zone,
    "OtpAttempts" integer,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE "ClientRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text,
    "Telegram" text,
    "BudgetRange" text,
    "ProjectType" text,
    "Message" text NOT NULL,
    "Status" text,
    "IsRead" boolean NOT NULL,
    "InternalNotes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_ClientRequests" PRIMARY KEY ("Id")
);


CREATE TABLE "PortfolioProjects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "VideoUrl" text,
    "Thumb" text,
    "ThumbFull" text,
    "Tags" text,
    "Views" integer,
    "ClientName" text,
    "ProjectDate" timestamp with time zone,
    "Duration" text,
    "IsFeatured" boolean,
    "Visibility" text,
    "ProjectType" text,
    "Industry" text,
    "Skills" text,
    "Challenge" text,
    "Solution" text,
    "Result" text,
    "Testimonial" text,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_PortfolioProjects" PRIMARY KEY ("Id")
);


CREATE TABLE "Pricings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BaseRate" numeric NOT NULL,
    "ComplexityBasic" numeric NOT NULL,
    "ComplexityMedium" numeric NOT NULL,
    "ComplexityHigh" numeric NOT NULL,
    "RateMotion" numeric NOT NULL,
    "RateExplainer" numeric NOT NULL,
    "RateProduction" numeric NOT NULL,
    "RateThreeD" numeric NOT NULL,
    "DeliveryDaysBasic" integer NOT NULL,
    "DeliveryDaysMedium" integer NOT NULL,
    "DeliveryDaysHigh" integer NOT NULL,
    "UrgentMultiplier" numeric NOT NULL,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_Pricings" PRIMARY KEY ("Id")
);


CREATE TABLE "Reviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Author" text NOT NULL,
    "Text" text NOT NULL,
    "Rating" integer NOT NULL,
    "Project" text,
    "Status" text NOT NULL,
    "Image" text,
    "Company" text,
    "Website" text,
    "SocialLink" text,
    "IsApproved" boolean NOT NULL,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id")
);


CREATE TABLE "Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Text" text NOT NULL,
    "Icon" text,
    "VideoUrl" text,
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "Price" numeric NOT NULL,
    "FeaturesJson" text,
    "MainTitle" text,
    "Description" text,
    "SecondaryDescription" text,
    "GroupsJson" text,
    "ProcessJson" text,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
);


CREATE TABLE "SiteSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HeroTitle" text,
    "HeroSubtitle" text,
    "HeroVideoUrl" text,
    "CtaText" text,
    "CtaLink" text,
    "SiteName" text,
    "LogoUrl" text,
    "SeoDescription" text,
    "SocialInstagram" text,
    "SocialBehance" text,
    "SocialDribbble" text,
    "SocialLinkedIn" text,
    "GalleryAutoplay" boolean NOT NULL,
    "HeroVideoOpacity" double precision NOT NULL,
    "HeroTypedText" text,
    "HeroTypedColor" text,
    "TelegramLink" text,
    "AiEnabled" boolean NOT NULL,
    "AiApiKey" text,
    "AiSystemPrompt" text,
    "AiWelcomeMessage" text,
    "NotifyEmailEnabled" boolean NOT NULL,
    "NotifyEmailAddress" text,
    "NotifyTelegramEnabled" boolean NOT NULL,
    "NotifyTelegramBotToken" text,
    "NotifyTelegramChatId" text,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_SiteSettings" PRIMARY KEY ("Id")
);


CREATE TABLE "SocialAccounts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Platform" text NOT NULL,
    "Value" text NOT NULL,
    "Icon" text NOT NULL,
    "Link" text NOT NULL,
    "IsVisible" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_SocialAccounts" PRIMARY KEY ("Id")
);


CREATE TABLE "TeamMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Role" text NOT NULL,
    "Image" text,
    "Bio" text,
    "Twitter" text,
    "Linkedin" text,
    "Instagram" text,
    "Skills" text,
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_TeamMembers" PRIMARY KEY ("Id")
);


CREATE TABLE "Translations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LanguageCode" text NOT NULL,
    "Key" text NOT NULL,
    "Value" text NOT NULL,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_Translations" PRIMARY KEY ("Id")
);


CREATE TABLE "VideoCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Slug" character varying(200),
    "Description" character varying(1000),
    "ServiceType" character varying(100),
    "IsActive" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_VideoCategories" PRIMARY KEY ("Id")
);


CREATE TABLE "VisitorLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Country" text,
    "CountryCode" text,
    "City" text,
    "Region" text,
    "Page" text,
    "Section" text,
    "SessionId" text,
    "IpAddress" text,
    "VisitedAt" timestamp with time zone NOT NULL,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_VisitorLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ResumeEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" text NOT NULL,
    "Title" text NOT NULL,
    "Subtitle" text NOT NULL,
    "DateRange" text NOT NULL,
    "Description" text NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "TeamMemberId" integer,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_ResumeEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ResumeEntries_TeamMembers_TeamMemberId" FOREIGN KEY ("TeamMemberId") REFERENCES "TeamMembers" ("Id")
);


CREATE TABLE "Videos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" text,
    "VideoUrl" character varying(500) NOT NULL,
    "Thumb" character varying(500),
    "ThumbFull" character varying(500),
    "Duration" character varying(50),
    "IsFeatured" boolean NOT NULL,
    "Views" integer NOT NULL,
    "Visibility" character varying(50) NOT NULL,
    "ClientName" character varying(200),
    "ProjectDate" timestamp with time zone,
    "Tags" character varying(500),
    "CategoryId" integer,
    "Createdby" text,
    "CreatedbyDate" date,
    "Updatedby" text,
    "UpdatedbyDate" date,
    CONSTRAINT "PK_Videos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Videos_VideoCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "VideoCategories" ("Id")
);


INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('ab10f5a1-d176-4913-a57b-7ee73cc2fccf', 'e285a2f9-8f49-4a26-970a-4331ff084fbe', 'Admin', 'ADMIN');


INSERT INTO "AspNetUsers" ("Id", "AccessFailedCount", "ConcurrencyStamp", "Email", "EmailConfirmed", "LockoutEnabled", "LockoutEnd", "NormalizedEmail", "NormalizedUserName", "OtpAttempts", "OtpCode", "OtpExpiry", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TwoFactorEnabled", "UserName")
VALUES ('e01996a9-a4f1-43c0-97af-a32f1afcc124', 0, '27e23412-3f62-4a8b-970b-c76b4ac9aa33', 'Admin@gmail.com', TRUE, FALSE, NULL, 'ADMIN@GMAIL.COM', 'ADMIN@GMAIL.COM', NULL, NULL, NULL, 'AQAAAAIAAYagAAAAENL7nJTWAl+JwRAJHa1dBz7RkdLsCb0kQKkPs9vQw67lKE9197X62GcvI2melNY1tA==', NULL, FALSE, '2eecc36e-b47f-4aae-bbe2-b59f7311aea4', FALSE, 'Admin');


INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (1, 'ListUser', 'ListUser', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (2, 'CreateNewUser', 'CreateNewUser', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (3, 'UpdateUser', 'UpdateUser', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (4, 'UpdatePassword', 'UpdatePassword', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (5, 'AssignRole', 'AssignRole', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (6, 'ListRole', 'ListRole', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (7, 'CreateNewRole', 'CreateNewRole', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (8, 'UpdateRole', 'UpdateRole', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (9, 'AssignPermissions', 'AssignPermissions', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (10, 'ListCompanies', 'ListCompanies', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (11, 'CreateCompany', 'CreateCompany', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (12, 'EditCompany', 'EditCompany', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (13, 'SearchCompany', 'SearchCompany', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (14, 'ViewLicences', 'ViewLicences', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (15, 'AddLicences', 'AddLicences', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (16, 'EditLicences', 'EditLicences', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (17, 'Licenceshistory', 'Licenceshistory', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (18, 'Viewlicenceshistory', 'Viewlicenceshistory', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (19, 'PrintJawaz', 'PrintJawaz', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (20, 'Listcatagories', 'Listcatagories', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (21, 'AddCatagory', 'AddCatagory', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');
INSERT INTO "AspNetRoleClaims" ("Id", "ClaimType", "ClaimValue", "RoleId")
VALUES (22, 'EditCatagory', 'EditCatagory', 'ab10f5a1-d176-4913-a57b-7ee73cc2fccf');


INSERT INTO "AspNetUserRoles" ("RoleId", "UserId")
VALUES ('ab10f5a1-d176-4913-a57b-7ee73cc2fccf', 'e01996a9-a4f1-43c0-97af-a32f1afcc124');


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE INDEX "IX_ResumeEntries_TeamMemberId" ON "ResumeEntries" ("TeamMemberId");


CREATE INDEX "IX_Videos_CategoryId" ON "Videos" ("CategoryId");


SELECT setval(
    pg_get_serial_sequence('"AspNetRoleClaims"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "AspNetRoleClaims") + 1,
        nextval(pg_get_serial_sequence('"AspNetRoleClaims"', 'Id'))),
    false);


